# 99 — Završna validacija integrisanog profila na FLEURS (30) i prirodnom srpskom govoru (40 snimaka)

**Skup:** lokalnih 30 WAV snimaka `audio/03_srpski_engleski/fleurs/srpski/fleurs_<ID>_sr.wav`. Originalne reference se učitavaju iz FLEURS `sr_rs/test.tsv` (ili proverene CSV tabele iz eksperimenta 03). **Nikada se ne koriste ASR hipoteze kao reference.**

Profil se učitava iz rezultata 08, a streaming mehanizam odgovara eksperimentu 07. Izbor profila ne sme se menjati nakon uvida u ove rezultate. Pošto su isti FLEURS primeri ranije korišćeni u eksperimentu 03, ovaj test nije potpuno nezavisan od svih eksperimenata rada, ali jeste zaseban skup od 40 prirodnih srpskih snimaka i pet snimaka eksperimenta 07.

Za prvi prolaz potreban je internet samo ako `sr_rs_test.tsv` nije već sačuvan lokalno. Nema ponovnog preuzimanja audio-snimaka.

**Dodatno poređenje:** isti model i dekodiranje na celom WAV-u bez streaming segmentacije, bez preklopa i bez `initial_prompt`. Čuvaju se odvojeni CSV rezultati i uporedna tabela. Za ceo WAV TTFR je procenjen kao trajanje celog snimka + vreme dekodiranja (batch rezultat, nije streaming TTFR).

In [1]:
from pathlib import Path
import time, re, unicodedata, math, wave
import numpy as np
import pandas as pd
from scipy.signal import resample_poly
from faster_whisper import WhisperModel
from jiwer import wer, process_words
from IPython.display import display

In [2]:
# Putanje: notebook pokrenuti iz projekta ili foldera notebooks.
NOTEBOOK_DIR = Path.cwd().resolve()
PROJECT_ROOT = NOTEBOOK_DIR.parent if NOTEBOOK_DIR.name.lower() == "notebooks" else NOTEBOOK_DIR
AUDIO_DIR = PROJECT_ROOT / "audio" / "03_srpski_engleski" / "fleurs" / "srpski"
FLEURS_RAW_DIR = PROJECT_ROOT / "audio" / "03_srpski_engleski" / "fleurs" / "arhive"
REZULTATI_DIR = PROJECT_ROOT / "rezultati" / "99_validacija_FLEURS_srpski"
PROFIL_CSV = PROJECT_ROOT / "rezultati" / "08_automatski_izbor_optimalne_konfiguracije" / "08_konacni_preporuceni_profil.csv"
REZULTATI_DIR.mkdir(parents=True, exist_ok=True)

if not PROFIL_CSV.is_file():
    raise FileNotFoundError(f"Pokreni prvo skriptu 08: nedostaje {PROFIL_CSV}")
p = pd.read_csv(PROFIL_CSV, encoding="utf-8-sig")
if not {"Parametar", "Preporučena vrednost"}.issubset(p.columns):
    raise ValueError("CSV profila iz 08 nema očekivane kolone")
profil = dict(zip(p["Parametar"], p["Preporučena vrednost"]))
def param(n):
    x = profil.get(n)
    if pd.isna(x) or str(x).strip().lower() in {"", "nije određeno", "none", "nan"}:
        raise ValueError(f"Skripta 08 nije odredila parametar: {n}")
    return x
MODEL_SIZE = str(param("Model")).strip().lower()
COMPUTE_TYPE = str(param("Kvantizacija")).strip().lower()
DEVICE = str(param("Uređaj")).strip().lower()
LANGUAGE = str(param("Jezik")).strip().lower()
BEAM_SIZE = int(param("Beam size"))
VAD_FILTER = {"ON":True,"OFF":False}.get(str(param("VAD default")).upper())
if VAD_FILTER is None: raise ValueError("VAD default mora biti ON ili OFF")
REZIM = str(param("Streaming režim")).strip()
CHUNK_SECONDS = int(param("Streaming chunk [s]"))
OVERLAP_SEC = float(param("Streaming overlap [s]"))
PROMPT_MAX_RECI = int(param("Streaming prompt max reči"))
REZIMI = {"A_bez_preklopa_bez_konteksta":(False,False), "B_samo_preklop":(True,False),
          "C_samo_kontekst":(False,True), "D_preklop_i_kontekst":(True,True)}
if REZIM not in REZIMI: raise ValueError(f"Nepoznat streaming režim: {REZIM}")
OVERLAP_ON, PROMPT_ON = REZIMI[REZIM]
if CHUNK_SECONDS not in (2,5,10): raise ValueError("Neočekivani chunk iz 08")
if OVERLAP_SEC != (1.0 if OVERLAP_ON else 0.0): raise ValueError("Overlap i režim se ne slažu")
if PROMPT_MAX_RECI != (8 if PROMPT_ON else 0): raise ValueError("Prompt i režim se ne slažu")
if BEAM_SIZE < 1: raise ValueError("Beam size mora biti pozitivan")
MAX_NEW_TOKENS = 48
MAX_RECI_PO_SEKUNDI = 4.0
WHISPER_SAMPLE_RATE = 16000
print("PROFIL IZ 08:", {"model":MODEL_SIZE,"compute":COMPUTE_TYPE,"beam":BEAM_SIZE,"VAD":VAD_FILTER,
                          "rezim":REZIM,"korak_s":CHUNK_SECONDS,"overlap_s":OVERLAP_SEC,"prompt_reci":PROMPT_MAX_RECI})
if (MODEL_SIZE, COMPUTE_TYPE, BEAM_SIZE, VAD_FILTER) != ("base", "int8", 1, False):
    print("NAPOMENA: 07 je rangirao streaming na base/int8, beam=1, VAD=False; ovde proveravamo prenos na drugi profil.")

if LANGUAGE not in ("sr", "serbian"):
    raise ValueError(f"Ova validacija je samo za srpski FLEURS; profil iz 08 ima jezik={LANGUAGE!r}")
LANGUAGE = "sr"

PROFIL IZ 08: {'model': 'small', 'compute': 'int8', 'beam': 5, 'VAD': True, 'rezim': 'D_preklop_i_kontekst', 'korak_s': 5, 'overlap_s': 1.0, 'prompt_reci': 8}
NAPOMENA: 07 je rangirao streaming na base/int8, beam=1, VAD=False; ovde proveravamo prenos na drugi profil.

## Učitavanje 30 FLEURS referenci

Prioritet je zvanični FLEURS `sr_rs/test.tsv`, identičan izvoru iz notebook-a 03. Ako nije lokalno dostupan, preuzima se samo mali TSV metapodatak. Uparivanje se vrši **isključivo prema numeričkom ID-ju**, a ne prema redosledu redova. Skripta prekida rad ako neki ID nedostaje ili je referenca prazna.

**Važno:** FLEURS numerički ID može da se ponovi. Kada postoji više TSV redova za isti ID, originalni `Filename_SR` iz `03_fleurs_parovi_i_reference.csv` služi za jednoznačno povezivanje sa lokalnim WAV-om. Bez manifesta skripta neće nagađati referencu.

In [3]:
import csv
import requests

EXPECTED_IDS = [1687,1689,1702,1722,1725,1782,1794,1796,1807,1810,
                1826,1828,1829,1845,1866,1877,1882,1895,1900,1904,
                1910,1921,1927,1936,1941,1943,1978,1983,1985,2006]

FLEURS_RAW_DIR.mkdir(parents=True, exist_ok=True)
TSV_PATH = FLEURS_RAW_DIR / "sr_rs_test.tsv"
TSV_URL = "https://huggingface.co/datasets/google/fleurs/resolve/main/data/sr_rs/test.tsv"

if not TSV_PATH.is_file():
    print("Originalni FLEURS TSV nije lokalno dostupan; preuzimam metapodatke...")
    r = requests.get(TSV_URL, timeout=90)
    r.raise_for_status()
    if len(r.content) < 100:
        raise RuntimeError("Preuzeti TSV je neočekivano mali")
    TSV_PATH.write_bytes(r.content)

# FLEURS sentence ID nije nužno jedinstven: isti ID može imati više WAV redova.
# Za ranije izdvojene WAV fajlove iz 03 merodavan je sačuvani manifest
# (ID + originalni filename), a ne proizvoljni prvi/poslednji TSV red.
from collections import defaultdict
meta_rows = defaultdict(list)
with TSV_PATH.open("r", encoding="utf-8-sig", newline="") as f:
    for line_no, cols in enumerate(csv.reader(f, delimiter="\t"), 1):
        if not cols or not any(x.strip() for x in cols):
            continue
        if cols[0].strip().lower() in ("id", "sentence_id"):
            continue
        if len(cols) < 4:
            raise ValueError(f"TSV red {line_no}: očekivane najmanje 4 kolone")
        try:
            sid = int(cols[0].strip())
        except ValueError as exc:
            raise ValueError(f"Neispravan ID u TSV redu {line_no}") from exc
        if sid not in EXPECTED_IDS:
            continue
        ref = cols[3].strip() or cols[2].strip()
        meta_rows[sid].append({"filename": cols[1].strip(), "ref": ref})

# Skripta 03 snima originalni filename i referencu za svaki lokalni WAV.
manifest_path = PROJECT_ROOT / "rezultati" / "03_srpski_engleski" / "03_fleurs_parovi_i_reference.csv"
manifest_candidates = sorted((PROJECT_ROOT / "rezultati").rglob("03_fleurs_parovi_i_reference.csv"))
if manifest_path.is_file():
    manifest_candidates = [manifest_path] + [p for p in manifest_candidates if p != manifest_path]

manifest = {}
for path in manifest_candidates:
    df_manifest = pd.read_csv(path, encoding="utf-8-sig", keep_default_na=False)
    needed = {"FLEURS_ID_SR", "Filename_SR", "Referenca_SR"}
    if not needed.issubset(df_manifest.columns):
        continue
    for row in df_manifest.to_dict("records"):
        try:
            sid = int(row["FLEURS_ID_SR"])
        except (ValueError, TypeError):
            continue
        if sid not in EXPECTED_IDS:
            continue
        item = {"filename": str(row["Filename_SR"]).strip(),
                "ref": str(row["Referenca_SR"]).strip()}
        if sid in manifest and manifest[sid] != item:
            raise ValueError(f"Različiti manifesti iz 03 daju različite podatke za ID {sid}; proveri {path}")
        manifest[sid] = item

meta = {}
for sid in EXPECTED_IDS:
    rows = meta_rows.get(sid, [])
    if not rows:
        raise ValueError(f"ID {sid} ne postoji u originalnom TSV-u")
    if sid in manifest:
        expected_filename = Path(manifest[sid]["filename"].replace("\\", "/")).name
        matches = [r for r in rows if Path(r["filename"].replace("\\", "/")).name == expected_filename]
        if len(matches) != 1:
            raise ValueError(f"ID {sid}: originalni WAV '{expected_filename}' iz manifesta 03 nije jednoznačno pronađen u TSV-u")
        chosen = matches[0]
        if chosen["ref"] != manifest[sid]["ref"]:
            raise ValueError(f"ID {sid}: referenca iz manifesta 03 ne slaže se sa originalnim TSV-om")
    elif len(rows) == 1:
        chosen = rows[0]
    else:
        raise ValueError(
            f"ID {sid} ima {len(rows)} redova u FLEURS TSV-u. "
            "Za pouzdano uparivanje WAV-a i reference potreban je "
            "03_fleurs_parovi_i_reference.csv iz eksperimenta 03 u folderu rezultati/. "
            "Bez njega nije moguće pouzdano izabrati ispravan red.")
    if not chosen["ref"]:
        raise ValueError(f"Prazna originalna referenca za ID {sid}")
    meta[sid] = chosen
print("Reference uparene po originalnom filename-u kada je ID višeznačan.")

wav_files = sorted(AUDIO_DIR.glob("fleurs_*_sr.wav"))
actual_ids = set()
for wav in wav_files:
    m = re.fullmatch(r"fleurs_(\d+)_sr\.wav", wav.name)
    if m is None:
        raise ValueError(f"Neočekivano ime WAV datoteke: {wav.name}")
    actual_ids.add(int(m.group(1)))
if actual_ids != set(EXPECTED_IDS) or len(wav_files) != 30:
    raise ValueError(f"Očekuje se tačno 30 navedenih WAV datoteka. "
                     f"Nedostaju: {sorted(set(EXPECTED_IDS)-actual_ids)}; "
                     f"višak: {sorted(actual_ids-set(EXPECTED_IDS))}")

missing_refs = [sid for sid in EXPECTED_IDS if sid not in meta or not meta[sid]['ref']]
if missing_refs:
    raise ValueError(f"Nedostaju originalne FLEURS reference za ID-jeve: {missing_refs}")

test_set = [dict(broj=sid, audio=str(AUDIO_DIR / f"fleurs_{sid}_sr.wav"),
                 ref=meta[sid]['ref'], govornik="FLEURS", grupa="FLEURS test")
            for sid in EXPECTED_IDS]

reference_df = pd.DataFrame([dict(FLEURS_ID=x['broj'], Audio=Path(x['audio']).name,
                                  Originalni_fleurs_filename=meta[x['broj']]['filename'],
                                  Referenca=x['ref']) for x in test_set])
reference_df.to_csv(REZULTATI_DIR / '99_fleurs_originalne_reference.csv', index=False, encoding='utf-8-sig')
display(reference_df)
print(f"Učitano {len(test_set)} originalnih FLEURS referenci iz: {TSV_PATH}")

Reference uparene po originalnom filename-u kada je ID višeznačan.

,FLEURS_ID,Audio,Originalni_fleurs_filename,Referenca
0,1687,fleurs_1687_sr.wav,2242979381176440686.wav,segregacija i rekombinovanje utiču na stalno m...
1,1689,fleurs_1689_sr.wav,9672695547465118938.wav,evropa je relativno mali kontinent ali sa mnog...
2,1702,fleurs_1702_sr.wav,2177115204693269186.wav,za samo dve nedelje amerikanci i snage slobodn...
3,1722,fleurs_1722_sr.wav,16662942048574661201.wav,kuomo koji ima 53 godine postao je guverner ra...
4,1725,fleurs_1725_sr.wav,8068863430427289355.wav,asus eee pc koji je ranije predstavljen širom ...
5,1782,fleurs_1782_sr.wav,13699557440731877072.wav,takođe je između svake dinastije bilo nestabil...
6,1794,fleurs_1794_sr.wav,378448169463282643.wav,civilizacija je jedinstvena kultura koju deli ...
7,1796,fleurs_1796_sr.wav,4766444613799711778.wav,sediment je bio neophodan za stvaranje peščani...
8,1807,fleurs_1807_sr.wav,8898181184818554807.wav,italijanski je takođe svakodnevni jezik koji k...
9,1810,fleurs_1810_sr.wav,11809056696844964165.wav,guverner kalifornije arnold švarceneger potpis...
10,1826,fleurs_1826_sr.wav,15661241027703166907.wav,nakon nesreće gibson je prevezen u bolnicu ali...
11,1828,fleurs_1828_sr.wav,11011658457297324786.wav,ako u pretragu na internetu ukucate kurs nepri...
12,1829,fleurs_1829_sr.wav,13497589697745231148.wav,putnici koji idu u zemlje sa visokim porezima ...
13,1845,fleurs_1845_sr.wav,2461322917604109150.wav,putovali su natrag u pariz kočijom okruženi ru...
14,1866,fleurs_1866_sr.wav,13085845417135633376.wav,pre svega većina jahača nosi čizme za jahanje ...
15,1877,fleurs_1877_sr.wav,7458384565186706630.wav,тренутна сенаторка и прва дама аргентине крист...
16,1882,fleurs_1882_sr.wav,17436563732262735729.wav,naučnici se nadaju da će razumeti kako se plan...
17,1895,fleurs_1895_sr.wav,4041359467137630141.wav,kako je znanje grčkog opadalo zapad se našao o...
18,1900,fleurs_1900_sr.wav,12781466767444155566.wav,zapravo teško ju je pronaći čak i ako neko zna...
19,1904,fleurs_1904_sr.wav,17913261368920506986.wav,međutim zbog sporih kanala komunikacije stilov...
20,1910,fleurs_1910_sr.wav,7727106597586045957.wav,parižani imaju reputaciju da su egocentrični n...
21,1921,fleurs_1921_sr.wav,11468751733696581296.wav,s druge strane snežni i ledeni uslovi su norma...
22,1927,fleurs_1927_sr.wav,16879992715416558746.wav,ејнџел 2006 објашњава приступ континуума као м...
23,1936,fleurs_1936_sr.wav,14848945984935032920.wav,peri je izjavio vratio bih se u teksas da proc...
24,1941,fleurs_1941_sr.wav,4226489578664968146.wav,ovi parovi mogu da odluče da isplaniraju usvaj...
25,1943,fleurs_1943_sr.wav,15354482596140161763.wav,što je niža tenzija to je pozitivnija životna ...
26,1978,fleurs_1978_sr.wav,13271494138809527920.wav,time je za springbokse završen niz od pet pora...
27,1983,fleurs_1983_sr.wav,9204834830995490373.wav,reč civilizacija potiče od latinske reči civil...
28,1985,fleurs_1985_sr.wav,15945371416486877786.wav,povezan je sa ali obično ne uključuje ski-ture...
29,2006,fleurs_2006_sr.wav,11617080208711120813.wav,elementi kao što su kalcijum i kalijum se smat...

Učitano 30 originalnih FLEURS referenci iz: D:\0000000000MasterRad\aleksandar_jovanović_Faster-Whisper&CTranslate2_2026\Projekat2ASR\audio\03_srpski_engleski\fleurs\arhive\sr_rs_test.tsv

In [4]:
if len(test_set) != 30 or len({x["broj"] for x in test_set}) != 30:
    raise AssertionError("Očekuje se tačno 30 jedinstvenih FLEURS snimaka")
for x in test_set:
    if not Path(x['audio']).is_file():
        raise FileNotFoundError(x['audio'])
    if not x['ref'].strip():
        raise ValueError(f"Prazna referenca: {x['broj']}")
print("Provera svih 30 WAV datoteka i referenci: OK")

Provera svih 30 WAV datoteka i referenci: OK

## Audio, normalizacija i streaming algoritam

Audio se resampluje na 16 kHz, koristi se algoritam preklapanja i konteksta iz 07, sa profilom iz 08. Normalizacija srpskog pisma je usklađena sa eksperimentom 03 (ćirilica → latinica).

In [5]:
import soundfile as sf
import numpy as np

def ucitaj_wav_pcm16(putanja):
    audio, sample_rate = sf.read(
        str(putanja),
        dtype="float32",
        always_2d=False
    )

    # Stereo -> mono
    if audio.ndim == 2:
        audio = np.mean(audio, axis=1)

    return np.asarray(audio, dtype=np.float32), sample_rate

def resampluj_na_16k(audio, original_sr):
    if original_sr == WHISPER_SAMPLE_RATE:
        return audio.astype(np.float32)

    g = math.gcd(int(original_sr), WHISPER_SAMPLE_RATE)
    up = WHISPER_SAMPLE_RATE // g
    down = int(original_sr) // g

    audio_16k = resample_poly(audio, up, down).astype(np.float32)
    return np.ascontiguousarray(audio_16k)

PRESLOVLJAVANJE = {
    "а":"a", "б":"b", "в":"v", "г":"g", "д":"d", "ђ":"đ",
    "е":"e", "ж":"ž", "з":"z", "и":"i", "ј":"j", "к":"k",
    "л":"l", "љ":"lj", "м":"m", "н":"n", "њ":"nj", "о":"o",
    "п":"p", "р":"r", "с":"s", "т":"t", "ћ":"ć", "у":"u",
    "ф":"f", "х":"h", "ц":"c", "ч":"č", "џ":"dž", "ш":"š",
}
TRANSLIT = str.maketrans(PRESLOVLJAVANJE)

def normalizuj_tekst(text):
    s = unicodedata.normalize("NFKC", str(text)).lower()
    s = s.translate(TRANSLIT)
    s = "".join(ch if (ch.isalnum() or ch.isspace()) else " " for ch in s)
    return " ".join(s.split())

assert normalizuj_tekst("Љубав, Његош и Џем!") == "ljubav njegoš i džem"
assert normalizuj_tekst("Тест test 123.") == "test test 123"

In [6]:
def tokeni(s):
    return normalizuj_tekst(s).split()

def ukloni_zajednicki_prefiks(prethodno, novo, max_reci=25,
                              dozvoli_jednu=False):
    """Determinističko poravnanje sufiksa/prefiksa, bez referentnog teksta."""
    a, b = tokeni(prethodno), tokeni(novo)
    limit = min(len(a), len(b), max_reci)
    poklapanje = next((k for k in range(limit, 0, -1)
                       if a[-k:] == b[:k]), 0)
    if poklapanje < (1 if dozvoli_jednu else 2):
        return novo.strip(), 0
    # Čuvamo originalne tokene, ne rekonstruišemo tekst iz normalizovanih reči.
    original = novo.split()
    if len(original) != len(b):
        # Različita tokenizacija: bezbednije je ne brisati.
        return novo.strip(), 0
    return " ".join(original[poklapanje:]), poklapanje

def izdvoji_tekst(segs, granica_lokalno, ima_preklop):
    delovi, sirovi = [], []
    granicni_kandidati = False
    for s in segs:
        if s.text.strip():
            sirovi.append(s.text.strip())
        if not ima_preklop or granica_lokalno <= 0:
            if s.text.strip():
                delovi.append(s.text.strip())
            continue
        words = getattr(s, "words", None)
        if words:
            zadrzane = []
            for w in words:
                a, b = float(w.start), float(w.end)
                if b <= granica_lokalno:
                    continue
                trajanje = max(b-a, 1e-6)
                novi_deo = max(0.0, b-max(a, granica_lokalno))/trajanje
                if a >= granica_lokalno or novi_deo >= MIN_NOVI_DEO_RECI:
                    zadrzane.append(w.word.strip())
                    if a < granica_lokalno:
                        granicni_kandidati = True
            if zadrzane:
                delovi.append(" ".join(zadrzane))
        elif float(s.end) <= granica_lokalno:
            continue
        elif float(s.start) >= granica_lokalno:
            if s.text.strip():
                delovi.append(s.text.strip())
        else:
            # Bez oznaka reči: sačuvaj neodređen segment,
            # tekstualno poravnanje će pokušati da ukloni duplikate.
            if s.text.strip():
                delovi.append(s.text.strip())
            granicni_kandidati = True
    return " ".join(delovi).strip(), " ".join(sirovi).strip(), granicni_kandidati

In [19]:
# Dekodiranje iz 07: isti parametri zaštite od ponavljanja, ali beam/VAD iz profila 08.
# VAD je eksplicitno preuzet iz 08; to je promena eksperimentalnih uslova u odnosu na 07.
MIN_NOVI_DEO_RECI = 0.40

def dekodiraj_segment(model, audio, prompt=None, max_tokens=48):
    kw = dict(language=LANGUAGE, task="transcribe", beam_size=BEAM_SIZE, temperature=0.0,
              vad_filter=VAD_FILTER, condition_on_previous_text=False,
              without_timestamps=False, word_timestamps=True,
              max_new_tokens=max_tokens, repetition_penalty=1.15,
              no_repeat_ngram_size=3)
    if prompt: kw["initial_prompt"] = prompt
    t0 = time.perf_counter()
    segs, _ = model.transcribe(np.ascontiguousarray(audio, dtype=np.float32), **kw)
    segs = list(segs)
    return segs, time.perf_counter() - t0

def transkribuj_u_chunkovima(model, audio_16k):
    sr = WHISPER_SAMPLE_RATE
    ukupno_s = len(audio_16k)/sr
    korak = int(round(CHUNK_SECONDS*sr))
    preklop = int(round(OVERLAP_SEC*sr)) if OVERLAP_ON else 0
    prihvaceno, chunk_rows = [], []
    prethodni_zavrsetak, first_finish = 0.0, None
    kontekst_pouzdan = True
    for j, start in enumerate(range(0, len(audio_16k), korak), 1):
        end = min(start+korak, len(audio_16k))
        ulaz_start = max(0, start-preklop)
        prompt = ' '.join(tokeni(' '.join(prihvaceno))[-PROMPT_MAX_RECI:]) if (PROMPT_ON and kontekst_pouzdan) else None
        segs, dt = dekodiraj_segment(model, audio_16k[ulaz_start:end], prompt)
        granica = (start-ulaz_start)/sr
        novi_tekst, sirovi_tekst, granicni_kandidati = izdvoji_tekst(segs, granica, OVERLAP_ON)
        prethodni = ' '.join(prihvaceno)
        novi_tekst, broj_duplih = ukloni_zajednicki_prefiks(
            prethodni, novi_tekst, dozvoli_jednu=granicni_kandidati
        ) if OVERLAP_ON else (novi_tekst, 0)
        odnos_reci = len(tokeni(novi_tekst)) / max((end-start)/sr, 0.01)
        kontekst_pouzdan = bool(novi_tekst.strip()) and odnos_reci <= MAX_RECI_PO_SEKUNDI
        if novi_tekst.strip(): prihvaceno.append(novi_tekst.strip())
        arrival = end/sr
        start_proc = max(arrival, prethodni_zavrsetak)
        finish = start_proc+dt
        prethodni_zavrsetak = finish
        if first_finish is None: first_finish = finish
        chunk_rows.append(dict(Chunk_ID=j, Audio_od_s=ulaz_start/sr, Novi_od_s=start/sr,
            Do_s=arrival, Ulaz_trajanje_s=(end-ulaz_start)/sr, Novi_trajanje_s=(end-start)/sr,
            Prompt_reci=len(prompt.split()) if prompt else 0,
            Kontekst_pouzdan=kontekst_pouzdan, Reci_po_s=odnos_reci,
            Izbaceno_duplih_reci=broj_duplih, Granicni_kandidati=granicni_kandidati,
            Sirovi_tekst=sirovi_tekst, Prihvaceni_tekst=novi_tekst,
            Inference_s=dt, RTF_novi=dt/((end-start)/sr), Arrival_s=arrival,
            Queue_s=start_proc-arrival, Result_delay_s=finish-arrival))
    if not chunk_rows: raise ValueError("Prazan audio zapis")
    return ' '.join(prihvaceno).strip(), chunk_rows, dict(
        Ukupno_inference_s=sum(x['Inference_s'] for x in chunk_rows),
        TTFR_s=first_finish, Max_queue_s=max(x['Queue_s'] for x in chunk_rows),
        Max_result_delay_s=max(x['Result_delay_s'] for x in chunk_rows),
        Final_tail_s=max(0,prethodni_zavrsetak-ukupno_s))


def transkribuj_ceo_snimak(model, audio_16k):
    """Jedan ASR poziv nad celim WAV-om; isti beam/VAD i zaštite kao streaming.
    Bez chunk granica, preklapanja, initial_prompt i tekstualnog deduplikovanja.
    """
    segs, inference_s = dekodiraj_segment(
    model, audio_16k, prompt=None, max_tokens=None
)
    tekst = " ".join(s.text.strip() for s in segs if s.text.strip()).strip()
    return tekst, inference_s

In [8]:
# Jedinični testovi bez ASR-a
assert ukloni_zajednicki_prefiks("sistem koristi mašinsko učenje", "mašinsko učenje za govor")[0] == "za govor"
assert ukloni_zajednicki_prefiks("sistem koristi mašinsko učenje", "učenje za govor", dozvoli_jednu=True)[0] == "za govor"
assert ukloni_zajednicki_prefiks("sistem koristi mašinsko učenje", "učenje za govor", dozvoli_jednu=False)[0] == "učenje za govor"
print("Testovi spajanja: OK")

Testovi spajanja: OK

## Pokretanje završne validacije na 30 srpskih FLEURS snimaka

Ovaj test je zaključan na gore navedene ID-jeve. Prvo izvršiti 08 i ne podešavati profil na osnovu dobijenih FLEURS WER vrednosti.

In [9]:
model = WhisperModel(MODEL_SIZE, device=DEVICE, compute_type=COMPUTE_TYPE)
# Warm-up izvan vremena pojedinačnih snimaka
prvi, sr0 = ucitaj_wav_pcm16(Path(test_set[0]["audio"]))
prvi = resampluj_na_16k(prvi, sr0)
_ = dekodiraj_segment(model, prvi[:min(len(prvi), 5*WHISPER_SAMPLE_RATE)])
print("Model učitan i zagrejan")

Model učitan i zagrejan

In [10]:
rezultati, chunk_rezultati = [], []
for i,item in enumerate(test_set,1):
    putanja = Path(item["audio"])
    audio,sr = ucitaj_wav_pcm16(putanja)
    audio = resampluj_na_16k(audio,sr)
    trajanje = len(audio)/WHISPER_SAMPLE_RATE
    t0 = time.perf_counter()
    hyp, rows, m = transkribuj_u_chunkovima(model,audio)
    ukupno_wall = time.perf_counter()-t0
    ref = item["ref"]
    vrednost = wer(normalizuj_tekst(ref),normalizuj_tekst(hyp))*100
    row = dict(Broj=item["broj"],Fajl=putanja.name,Govornik=item["govornik"],Grupa=item["grupa"],
               Model=MODEL_SIZE,Kvantizacija=COMPUTE_TYPE,Beam_size=BEAM_SIZE,VAD=VAD_FILTER,
               Rezim=REZIM,Chunk_s=CHUNK_SECONDS,Overlap_s=OVERLAP_SEC,Prompt_max_reci=PROMPT_MAX_RECI,
               Trajanje_s=trajanje,Broj_chunkova=len(rows),Referenca=ref,Transkript=hyp,
               WER_pct=vrednost,Vreme_s=ukupno_wall,RTF=ukupno_wall/trajanje,
               RTF_inference=m['Ukupno_inference_s']/trajanje,**m)
    rezultati.append(row)
    chunk_rezultati.extend(dict(Broj=item["broj"],Fajl=putanja.name,Rezim=REZIM,Chunk_s=CHUNK_SECONDS,**r) for r in rows)
    print(f"[{i:02d}/30] {putanja.name}: WER={vrednost:.2f}% RTF={row['RTF']:.3f} TTFR={m['TTFR_s']:.2f}s")
df = pd.DataFrame(rezultati)
df_chunks = pd.DataFrame(chunk_rezultati)
if len(df)!=30 or df['Broj'].nunique()!=30: raise AssertionError('Nepotpuna validacija')
df.to_csv(REZULTATI_DIR/'99_FLEURS_validacija_po_snimku.csv',index=False,encoding='utf-8-sig')
df_chunks.to_csv(REZULTATI_DIR/'99_FLEURS_validacija_chunkovi.csv',index=False,encoding='utf-8-sig')
display(df[['Broj','Fajl','WER_pct','Vreme_s','RTF','RTF_inference','TTFR_s','Broj_chunkova']].round(3))

[01/30] fleurs_1687_sr.wav: WER=57.14% RTF=1.443 TTFR=12.09s
[02/30] fleurs_1689_sr.wav: WER=32.26% RTF=0.852 TTFR=8.63s
[03/30] fleurs_1702_sr.wav: WER=44.44% RTF=1.181 TTFR=8.73s
[04/30] fleurs_1722_sr.wav: WER=45.45% RTF=0.792 TTFR=8.76s
[05/30] fleurs_1725_sr.wav: WER=71.43% RTF=1.285 TTFR=11.62s
[06/30] fleurs_1782_sr.wav: WER=51.72% RTF=1.162 TTFR=12.65s
[07/30] fleurs_1794_sr.wav: WER=55.56% RTF=1.247 TTFR=11.99s
[08/30] fleurs_1796_sr.wav: WER=26.32% RTF=1.172 TTFR=11.74s
[09/30] fleurs_1807_sr.wav: WER=66.67% RTF=1.128 TTFR=11.46s
[10/30] fleurs_1810_sr.wav: WER=61.11% RTF=1.229 TTFR=11.56s
[11/30] fleurs_1826_sr.wav: WER=45.45% RTF=1.525 TTFR=12.83s
[12/30] fleurs_1828_sr.wav: WER=46.67% RTF=1.192 TTFR=8.87s
[13/30] fleurs_1829_sr.wav: WER=58.33% RTF=1.281 TTFR=11.93s
[14/30] fleurs_1845_sr.wav: WER=57.89% RTF=1.485 TTFR=11.81s
[15/30] fleurs_1866_sr.wav: WER=20.00% RTF=1.357 TTFR=11.78s
[16/30] fleurs_1877_sr.wav: WER=53.12% RTF=1.013 TTFR=8.70s
[17/30] fleurs_1882_sr.wav: WER=28.00% RTF=1.024 TTFR=8.77s
[18/30] fleurs_1895_sr.wav: WER=56.25% RTF=1.205 TTFR=11.74s
[19/30] fleurs_1900_sr.wav: WER=36.84% RTF=1.226 TTFR=11.99s
[20/30] fleurs_1904_sr.wav: WER=42.11% RTF=1.186 TTFR=11.70s
[21/30] fleurs_1910_sr.wav: WER=77.78% RTF=1.240 TTFR=11.99s
[22/30] fleurs_1921_sr.wav: WER=77.27% RTF=1.093 TTFR=11.93s
[23/30] fleurs_1927_sr.wav: WER=50.00% RTF=0.727 TTFR=8.48s
[24/30] fleurs_1936_sr.wav: WER=50.00% RTF=0.858 TTFR=8.59s
[25/30] fleurs_1941_sr.wav: WER=66.67% RTF=1.070 TTFR=9.48s
[26/30] fleurs_1943_sr.wav: WER=26.32% RTF=0.768 TTFR=8.74s
[27/30] fleurs_1978_sr.wav: WER=46.15% RTF=0.873 TTFR=8.75s
[28/30] fleurs_1983_sr.wav: WER=57.14% RTF=0.901 TTFR=8.92s
[29/30] fleurs_1985_sr.wav: WER=42.86% RTF=0.757 TTFR=8.74s
[30/30] fleurs_2006_sr.wav: WER=35.00% RTF=1.469 TTFR=12.27s

,Broj,Fajl,WER_pct,Vreme_s,RTF,RTF_inference,TTFR_s,Broj_chunkova
0,1687,fleurs_1687_sr.wav,57.143,10.995,1.443,1.443,12.089,2
1,1689,fleurs_1689_sr.wav,32.258,15.018,0.852,0.852,8.630,4
2,1702,fleurs_1702_sr.wav,44.444,14.201,1.181,1.181,8.728,3
3,1722,fleurs_1722_sr.wav,45.455,11.165,0.792,0.792,8.762,3
4,1725,fleurs_1725_sr.wav,71.429,18.125,1.285,1.285,11.617,3
5,1782,fleurs_1782_sr.wav,51.724,19.404,1.162,1.162,12.650,4
6,1794,fleurs_1794_sr.wav,55.556,10.847,1.247,1.247,11.994,2
7,1796,fleurs_1796_sr.wav,26.316,10.763,1.172,1.172,11.738,2
8,1807,fleurs_1807_sr.wav,66.667,13.628,1.128,1.128,11.460,3
9,1810,fleurs_1810_sr.wav,61.111,14.087,1.229,1.229,11.564,3
10,1826,fleurs_1826_sr.wav,45.455,10.980,1.525,1.525,12.832,2
11,1828,fleurs_1828_sr.wav,46.667,14.185,1.192,1.192,8.871,3
12,1829,fleurs_1829_sr.wav,58.333,14.454,1.281,1.281,11.930,3
13,1845,fleurs_1845_sr.wav,57.895,14.078,1.485,1.485,11.811,2
14,1866,fleurs_1866_sr.wav,20.000,10.095,1.357,1.357,11.780,2
15,1877,fleurs_1877_sr.wav,53.125,15.624,1.013,1.013,8.698,4
16,1882,fleurs_1882_sr.wav,28.000,14.843,1.024,1.024,8.767,3
17,1895,fleurs_1895_sr.wav,56.250,10.632,1.205,1.205,11.744,2
18,1900,fleurs_1900_sr.wav,36.842,10.812,1.226,1.226,11.986,2
19,1904,fleurs_1904_sr.wav,42.105,10.607,1.186,1.186,11.696,2
20,1910,fleurs_1910_sr.wav,77.778,10.617,1.240,1.240,11.992,2
21,1921,fleurs_1921_sr.wav,77.273,10.822,1.093,1.093,11.930,2
22,1927,fleurs_1927_sr.wav,50.000,10.767,0.727,0.726,8.477,3
23,1936,fleurs_1936_sr.wav,50.000,18.908,0.858,0.858,8.593,5
24,1941,fleurs_1941_sr.wav,66.667,7.660,1.070,1.070,9.481,2
25,1943,fleurs_1943_sr.wav,26.316,7.881,0.768,0.768,8.735,3
26,1978,fleurs_1978_sr.wav,46.154,7.260,0.873,0.873,8.753,2
27,1983,fleurs_1983_sr.wav,57.143,16.551,0.901,0.901,8.920,4
28,1985,fleurs_1985_sr.wav,42.857,11.777,0.757,0.757,8.740,4
29,2006,fleurs_2006_sr.wav,35.000,11.458,1.469,1.469,12.265,2

In [11]:
# Corpus WER: zbir edit operacija po snimku, bez lažnog poravnanja preko granica snimaka.
S=D=I=H=0
for r in df.itertuples():
    z = process_words(normalizuj_tekst(r.Referenca),normalizuj_tekst(r.Transkript))
    S+=z.substitutions; D+=z.deletions; I+=z.insertions; H+=z.hits
corpus_wer=100*(S+D+I)/(S+D+H)
rezime=pd.DataFrame([dict(Model=MODEL_SIZE,Kvantizacija=COMPUTE_TYPE,Beam_size=BEAM_SIZE,VAD=VAD_FILTER,
    Rezim=REZIM,Chunk_s=CHUNK_SECONDS,Overlap_s=OVERLAP_SEC,Prompt_max_reci=PROMPT_MAX_RECI,
    Broj_snimaka=len(df),Prosecan_WER_pct=df.WER_pct.mean(),Medijana_WER_pct=df.WER_pct.median(),
    Corpus_WER_pct=corpus_wer,Zamene=S,Brisanja=D,Umetanja=I,Referentne_reci=S+D+H,
    Prosecno_vreme_s=df.Vreme_s.mean(),Ukupno_vreme_s=df.Vreme_s.sum(),
    Prosecan_RTF=df.RTF.mean(),Prosecan_RTF_inference=df.RTF_inference.mean(),
    Prosecna_TTFR_s=df.TTFR_s.mean(),Prosecni_max_queue_s=df.Max_queue_s.mean(),
    Ukupno_chunkova=int(df.Broj_chunkova.sum()))])
rezime.to_csv(REZULTATI_DIR/'99_FLEURS_validacija_rezime.csv',index=False,encoding='utf-8-sig')
display(rezime.round(4))

,Model,Kvantizacija,Beam_size,VAD,Rezim,Chunk_s,Overlap_s,Prompt_max_reci,Broj_snimaka,Prosecan_WER_pct,...,Brisanja,Umetanja,Referentne_reci,Prosecno_vreme_s,Ukupno_vreme_s,Prosecan_RTF,Prosecan_RTF_inference,Prosecna_TTFR_s,Prosecni_max_queue_s,Ukupno_chunkova
0,small,int8,5,True,D_preklop_i_kontekst,5,1.0,8,30,49.532,...,45,31,634,12.6082,378.2469,1.1248,1.1247,10.5744,3.1743,83

## Poređenje sa transkripcijom celog snimka (bez segmentacije)

**Kontrolni uslovi:** isti FLEURS snimci, iste reference, isti učitani Whisper model, kvantizacija, beam i VAD, ista normalizacija. Razlikuje se samo način obrade: jedan poziv nad celim snimkom, bez streaming segmentacije, preklapanja i `initial_prompt`.  

**TTFR za ceo snimak:** u simulaciji je `trajanje WAV-a + vreme dekodiranja`, jer se rezultat ne može isporučiti pre kraja snimka. To nije direktno uporedivo sa interaktivnim streaming odzivom нити је stvarno merenje mikrofonskog sistema. **RTF** je vreme dekodiranja / trajanje audio-zapisa; vreme učitavanja i resamplovanja je isključeno iz oba pristupa. Ne menja se profil na osnovu ovog poređenja.

In [12]:
# Odvojena kontrolna evaluacija: ceo snimak, bez segmentacije.
rezultati_ceo = []
for i, item in enumerate(test_set, 1):
    putanja = Path(item["audio"])
    audio, sr = ucitaj_wav_pcm16(putanja)
    audio = resampluj_na_16k(audio, sr)
    trajanje = len(audio) / WHISPER_SAMPLE_RATE
    if trajanje <= 0:
        raise ValueError(f"Prazan WAV: {putanja}")
    # Merimo samo transkripciju; audio učitavanje i resamplovanje su van merenja.
    t0 = time.perf_counter()
    hyp, inference_s = transkribuj_ceo_snimak(model, audio)
    wall_s = time.perf_counter() - t0
    ref = item["ref"]
    z = process_words(normalizuj_tekst(ref), normalizuj_tekst(hyp))
    nref = z.substitutions + z.deletions + z.hits
    if nref == 0:
        raise ValueError(f"Referenca bez reči: {putanja.name}")
    row = dict(Broj=item["broj"], Fajl=putanja.name,
               Govornik=item["govornik"], Grupa=item["grupa"],
               Model=MODEL_SIZE, Kvantizacija=COMPUTE_TYPE,
               Beam_size=BEAM_SIZE, VAD=VAD_FILTER,
               Rezim="CEO_SNIMAK_BEZ_SEGMENTACIJE", Chunk_s=np.nan,
               Overlap_s=0.0, Prompt_max_reci=0,
               Trajanje_s=trajanje, Broj_chunkova=1,
               Referenca=ref, Transkript=hyp,
               WER_pct=100*(z.substitutions+z.deletions+z.insertions)/nref,
               Zamene=z.substitutions, Brisanja=z.deletions,
               Umetanja=z.insertions, Referentne_reci=nref,
               Vreme_s=wall_s, RTF=wall_s/trajanje,
               RTF_inference=inference_s/trajanje,
               Ukupno_inference_s=inference_s,
               TTFR_s=trajanje+inference_s,
               Max_queue_s=np.nan, Max_result_delay_s=np.nan,
               Final_tail_s=inference_s)
    rezultati_ceo.append(row)
    print(f"[CEO {i:02d}/30] {putanja.name}: WER={row['WER_pct']:.2f}% RTF={row['RTF']:.3f} vreme_do_rezultata={row['TTFR_s']:.2f}s")

df_ceo = pd.DataFrame(rezultati_ceo)
if len(df_ceo) != 30 or df_ceo['Broj'].nunique() != 30:
    raise AssertionError("Nepotpuna evaluacija celog snimka")
df_ceo.to_csv(REZULTATI_DIR / '99_FLEURS_ceo_snimak_po_snimku.csv', index=False, encoding='utf-8-sig')
display(df_ceo[['Broj','Fajl','WER_pct','Vreme_s','RTF','RTF_inference','TTFR_s']].round(3))

[CEO 01/30] fleurs_1687_sr.wav: WER=50.00% RTF=0.999 vreme_do_rezultata=15.24s
[CEO 02/30] fleurs_1689_sr.wav: WER=29.03% RTF=0.851 vreme_do_rezultata=32.61s
[CEO 03/30] fleurs_1702_sr.wav: WER=55.56% RTF=0.597 vreme_do_rezultata=19.19s
[CEO 04/30] fleurs_1722_sr.wav: WER=50.00% RTF=0.524 vreme_do_rezultata=21.49s
[CEO 05/30] fleurs_1725_sr.wav: WER=64.29% RTF=0.741 vreme_do_rezultata=24.55s
[CEO 06/30] fleurs_1782_sr.wav: WER=37.93% RTF=0.845 vreme_do_rezultata=30.82s
[CEO 07/30] fleurs_1794_sr.wav: WER=38.89% RTF=0.877 vreme_do_rezultata=16.33s
[CEO 08/30] fleurs_1796_sr.wav: WER=21.05% RTF=1.374 vreme_do_rezultata=21.79s
[CEO 09/30] fleurs_1807_sr.wav: WER=38.10% RTF=1.221 vreme_do_rezultata=26.83s
[CEO 10/30] fleurs_1810_sr.wav: WER=83.33% RTF=1.157 vreme_do_rezultata=24.71s
[CEO 11/30] fleurs_1826_sr.wav: WER=45.45% RTF=1.107 vreme_do_rezultata=15.17s
[CEO 12/30] fleurs_1828_sr.wav: WER=40.00% RTF=0.662 vreme_do_rezultata=19.78s
[CEO 13/30] fleurs_1829_sr.wav: WER=54.17% RTF=1.203 vreme_do_rezultata=24.85s
[CEO 14/30] fleurs_1845_sr.wav: WER=57.89% RTF=1.182 vreme_do_rezultata=20.69s
[CEO 15/30] fleurs_1866_sr.wav: WER=13.33% RTF=1.074 vreme_do_rezultata=15.43s
[CEO 16/30] fleurs_1877_sr.wav: WER=75.00% RTF=0.778 vreme_do_rezultata=27.41s
[CEO 17/30] fleurs_1882_sr.wav: WER=32.00% RTF=0.808 vreme_do_rezultata=26.22s
[CEO 18/30] fleurs_1895_sr.wav: WER=62.50% RTF=0.906 vreme_do_rezultata=16.81s
[CEO 19/30] fleurs_1900_sr.wav: WER=26.32% RTF=0.934 vreme_do_rezultata=17.05s
[CEO 20/30] fleurs_1904_sr.wav: WER=42.11% RTF=0.903 vreme_do_rezultata=17.01s
[CEO 21/30] fleurs_1910_sr.wav: WER=44.44% RTF=0.836 vreme_do_rezultata=15.72s
[CEO 22/30] fleurs_1921_sr.wav: WER=63.64% RTF=1.152 vreme_do_rezultata=21.30s
[CEO 23/30] fleurs_1927_sr.wav: WER=40.00% RTF=0.787 vreme_do_rezultata=26.49s
[CEO 24/30] fleurs_1936_sr.wav: WER=45.65% RTF=0.930 vreme_do_rezultata=42.53s
[CEO 25/30] fleurs_1941_sr.wav: WER=55.56% RTF=0.576 vreme_do_rezultata=11.29s
[CEO 26/30] fleurs_1943_sr.wav: WER=57.89% RTF=0.380 vreme_do_rezultata=14.16s
[CEO 27/30] fleurs_1978_sr.wav: WER=61.54% RTF=0.854 vreme_do_rezultata=15.43s
[CEO 28/30] fleurs_1983_sr.wav: WER=88.57% RTF=0.488 vreme_do_rezultata=27.33s
[CEO 29/30] fleurs_1985_sr.wav: WER=35.71% RTF=0.809 vreme_do_rezultata=28.15s
[CEO 30/30] fleurs_2006_sr.wav: WER=35.00% RTF=1.025 vreme_do_rezultata=15.80s

    Broj                Fajl  WER_pct  Vreme_s    RTF  RTF_inference  TTFR_s
0   1687  fleurs_1687_sr.wav   50.000    7.615  0.999          0.999  15.235
1   1689  fleurs_1689_sr.wav   29.032   14.990  0.851          0.851  32.610
2   1702  fleurs_1702_sr.wav   55.556    7.173  0.597          0.597  19.193
3   1722  fleurs_1722_sr.wav   50.000    7.388  0.524          0.524  21.488
4   1725  fleurs_1725_sr.wav   64.286   10.450  0.741          0.741  24.550
5   1782  fleurs_1782_sr.wav   37.931   14.117  0.845          0.845  30.817
6   1794  fleurs_1794_sr.wav   38.889    7.627  0.877          0.877  16.327
7   1796  fleurs_1796_sr.wav   21.053   12.609  1.374          1.374  21.789
8   1807  fleurs_1807_sr.wav   38.095   14.754  1.221          1.221  26.834
9   1810  fleurs_1810_sr.wav   83.333   13.254  1.157          1.157  24.714
10  1826  fleurs_1826_sr.wav   45.455    7.967  1.107          1.107  15.167
11  1828  fleurs_1828_sr.wav   40.000    7.878  0.662          0.662  19.778
12  1829  fleurs_1829_sr.wav   54.167   13.571  1.203          1.203  24.851
13  1845  fleurs_1845_sr.wav   57.895   11.207  1.182          1.182  20.687
14  1866  fleurs_1866_sr.wav   13.333    7.988  1.074          1.074  15.428
15  1877  fleurs_1877_sr.wav   75.000   11.993  0.778          0.778  27.413
16  1882  fleurs_1882_sr.wav   32.000   11.720  0.808          0.808  26.220
17  1895  fleurs_1895_sr.wav   62.500    7.987  0.906          0.906  16.807
18  1900  fleurs_1900_sr.wav   26.316    8.233  0.934          0.933  17.053
19  1904  fleurs_1904_sr.wav   42.105    8.070  0.903          0.903  17.010
20  1910  fleurs_1910_sr.wav   44.444    7.156  0.836          0.836  15.716
21  1921  fleurs_1921_sr.wav   63.636   11.404  1.152          1.152  21.304
22  1927  fleurs_1927_sr.wav   40.000   11.665  0.787          0.787  26.485
23  1936  fleurs_1936_sr.wav   45.652   20.491  0.930          0.930  42.531
24  1941  fleurs_1941_sr.wav   55.556    4.127  0.576          0.576  11.287
25  1943  fleurs_1943_sr.wav   57.895    3.896  0.380          0.380  14.156
26  1978  fleurs_1978_sr.wav   61.538    7.109  0.854          0.854  15.429
27  1983  fleurs_1983_sr.wav   88.571    8.966  0.488          0.488  27.326
28  1985  fleurs_1985_sr.wav   35.714   12.591  0.809          0.809  28.151
29  2006  fleurs_2006_sr.wav   35.000    7.997  1.025          1.025  15.797

In [13]:
# Dva režima na istih 30 referenci: uporedni corpus WER bez prelaska granica snimaka.
def sumiraj_nacin(tabela, naziv):
    s=d=i=h=0
    for r in tabela.itertuples():
        z = process_words(normalizuj_tekst(r.Referenca), normalizuj_tekst(r.Transkript))
        s+=z.substitutions; d+=z.deletions; i+=z.insertions; h+=z.hits
    return dict(Nacin=naziv, Model=MODEL_SIZE, Kvantizacija=COMPUTE_TYPE,
        Beam_size=BEAM_SIZE, VAD=VAD_FILTER, Broj_snimaka=len(tabela),
        Corpus_WER_pct=100*(s+d+i)/(s+d+h),
        Prosecan_WER_pct=tabela.WER_pct.mean(), Medijana_WER_pct=tabela.WER_pct.median(),
        Zamene=s, Brisanja=d, Umetanja=i, Referentne_reci=s+d+h,
        Prosecan_RTF=tabela.RTF.mean(), Prosecan_RTF_inference=tabela.RTF_inference.mean(),
        Prosecno_vreme_dekodiranja_s=tabela.Vreme_s.mean(),
        Prosecna_TTFR_s=tabela.TTFR_s.mean(),
        TTFR_definicija=('simulirano vreme do prvog chunk rezultata' if naziv=='STREAMING' else
                         'trajanje celog WAV + dekodiranje; batch rezultat'))

poredjenje = pd.DataFrame([sumiraj_nacin(df,'STREAMING'), sumiraj_nacin(df_ceo,'CEO_SNIMAK')])
poredjenje.to_csv(REZULTATI_DIR/'99_FLEURS_UPoredni_rezime.csv',index=False,encoding='utf-8-sig')
parovi = df[['Broj','Fajl','WER_pct','RTF','TTFR_s']].merge(
    df_ceo[['Broj','Fajl','WER_pct','RTF','TTFR_s']], on=['Broj','Fajl'],
    suffixes=('_streaming','_ceo'), validate='one_to_one')
parovi['Razlika_WER_pp_stream_minus_ceo'] = parovi.WER_pct_streaming - parovi.WER_pct_ceo
parovi['Razlika_RTF_stream_minus_ceo'] = parovi.RTF_streaming - parovi.RTF_ceo
parovi.to_csv(REZULTATI_DIR/'99_FLEURS_UPoredno_po_snimku.csv',index=False,encoding='utf-8-sig')
print('Uporedni rezultati (niži WER, RTF i TTFR su bolji, uz različito značenje TTFR):')
display(poredjenje[['Nacin','Broj_snimaka','Corpus_WER_pct','Prosecan_WER_pct','Prosecan_RTF','Prosecna_TTFR_s']].round(3))
print('Razlika corpus WER (streaming - ceo snimak), procentni poeni:',
      round(float(poredjenje.iloc[0].Corpus_WER_pct - poredjenje.iloc[1].Corpus_WER_pct), 3))
display(parovi.round(3))

Uporedni rezultati (niži WER, RTF i TTFR su bolji, uz različito značenje TTFR):

,Nacin,Broj_snimaka,Corpus_WER_pct,Prosecan_WER_pct,Prosecan_RTF,Prosecna_TTFR_s
0,STREAMING,30,49.211,49.532,1.125,10.574
1,CEO_SNIMAK,30,49.054,48.165,0.886,21.738

Razlika corpus WER (streaming - ceo snimak), procentni poeni: 0.158

,Broj,Fajl,WER_pct_streaming,RTF_streaming,TTFR_s_streaming,WER_pct_ceo,RTF_ceo,TTFR_s_ceo,Razlika_WER_pp_stream_minus_ceo,Razlika_RTF_stream_minus_ceo
0,1687,fleurs_1687_sr.wav,57.143,1.443,12.089,50.000,0.999,15.235,7.143,0.444
1,1689,fleurs_1689_sr.wav,32.258,0.852,8.630,29.032,0.851,32.610,3.226,0.002
2,1702,fleurs_1702_sr.wav,44.444,1.181,8.728,55.556,0.597,19.193,-11.111,0.585
3,1722,fleurs_1722_sr.wav,45.455,0.792,8.762,50.000,0.524,21.488,-4.545,0.268
4,1725,fleurs_1725_sr.wav,71.429,1.285,11.617,64.286,0.741,24.550,7.143,0.544
5,1782,fleurs_1782_sr.wav,51.724,1.162,12.650,37.931,0.845,30.817,13.793,0.317
6,1794,fleurs_1794_sr.wav,55.556,1.247,11.994,38.889,0.877,16.327,16.667,0.370
7,1796,fleurs_1796_sr.wav,26.316,1.172,11.738,21.053,1.374,21.789,5.263,-0.201
8,1807,fleurs_1807_sr.wav,66.667,1.128,11.460,38.095,1.221,26.834,28.571,-0.093
9,1810,fleurs_1810_sr.wav,61.111,1.229,11.564,83.333,1.157,24.714,-22.222,0.073
10,1826,fleurs_1826_sr.wav,45.455,1.525,12.832,45.455,1.107,15.167,0.000,0.418
11,1828,fleurs_1828_sr.wav,46.667,1.192,8.871,40.000,0.662,19.778,6.667,0.530
12,1829,fleurs_1829_sr.wav,58.333,1.281,11.930,54.167,1.203,24.851,4.167,0.078
13,1845,fleurs_1845_sr.wav,57.895,1.485,11.811,57.895,1.182,20.687,0.000,0.303
14,1866,fleurs_1866_sr.wav,20.000,1.357,11.780,13.333,1.074,15.428,6.667,0.283
15,1877,fleurs_1877_sr.wav,53.125,1.013,8.698,75.000,0.778,27.413,-21.875,0.235
16,1882,fleurs_1882_sr.wav,28.000,1.024,8.767,32.000,0.808,26.220,-4.000,0.215
17,1895,fleurs_1895_sr.wav,56.250,1.205,11.744,62.500,0.906,16.807,-6.250,0.300
18,1900,fleurs_1900_sr.wav,36.842,1.226,11.986,26.316,0.934,17.053,10.526,0.292
19,1904,fleurs_1904_sr.wav,42.105,1.186,11.696,42.105,0.903,17.010,-0.000,0.284
20,1910,fleurs_1910_sr.wav,77.778,1.240,11.992,44.444,0.836,15.716,33.333,0.404
21,1921,fleurs_1921_sr.wav,77.273,1.093,11.930,63.636,1.152,21.304,13.636,-0.059
22,1927,fleurs_1927_sr.wav,50.000,0.727,8.477,40.000,0.787,26.485,10.000,-0.061
23,1936,fleurs_1936_sr.wav,50.000,0.858,8.593,45.652,0.930,42.531,4.348,-0.072
24,1941,fleurs_1941_sr.wav,66.667,1.070,9.481,55.556,0.576,11.287,11.111,0.493
25,1943,fleurs_1943_sr.wav,26.316,0.768,8.735,57.895,0.380,14.156,-31.579,0.388
26,1978,fleurs_1978_sr.wav,46.154,0.873,8.753,61.538,0.854,15.429,-15.385,0.018
27,1983,fleurs_1983_sr.wav,57.143,0.901,8.920,88.571,0.488,27.326,-31.429,0.413
28,1985,fleurs_1985_sr.wav,42.857,0.757,8.740,35.714,0.809,28.151,7.143,-0.052
29,2006,fleurs_2006_sr.wav,35.000,1.469,12.265,35.000,1.025,15.797,0.000,0.444

In [14]:
najgori=df.sort_values('WER_pct',ascending=False).head(10)
display(najgori[['Broj','Fajl','WER_pct','RTF','Broj_chunkova']].round(3))
for r in najgori.itertuples():
    print(f"\n{r.Fajl} | WER={r.WER_pct:.2f}%\nREF: {r.Referenca}\nHYP: {r.Transkript}")

    Broj                Fajl  WER_pct    RTF  Broj_chunkova
20  1910  fleurs_1910_sr.wav   77.778  1.240              2
21  1921  fleurs_1921_sr.wav   77.273  1.093              2
4   1725  fleurs_1725_sr.wav   71.429  1.285              3
24  1941  fleurs_1941_sr.wav   66.667  1.070              2
8   1807  fleurs_1807_sr.wav   66.667  1.128              3
9   1810  fleurs_1810_sr.wav   61.111  1.229              3
12  1829  fleurs_1829_sr.wav   58.333  1.281              3
13  1845  fleurs_1845_sr.wav   57.895  1.485              2
0   1687  fleurs_1687_sr.wav   57.143  1.443              2
27  1983  fleurs_1983_sr.wav   57.143  0.901              4

fleurs_1910_sr.wav | WER=77.78%
REF: parižani imaju reputaciju da su egocentrični neljubazni i arogantni
HYP: Pariža nije reputaciju da svojegocentrični ne lj ljubezni i arrogantri.

fleurs_1921_sr.wav | WER=77.27%
REF: s druge strane snežni i ledeni uslovi su normalni u mnogim zemljama a saobraćaj se odvija uglavnom bez prekida tokom cele godine
HYP: S druge strane, snježnije ledene uslovi su normalni u nogim z Zemljamo. Savreć je sodvijel u glavnom besprejke da je to kao celek godine

fleurs_1725_sr.wav | WER=71.43%
REF: asus eee pc koji je ranije predstavljen širom sveta iz razloga uštede novca i funkcionalnosti postao je glavna tema u toku aj-ti meseca u tajpeju 2007. godine
HYP: Asus E-E-E pisi koji je ranje prestavljano što je. svep teh zrazove uštajde noci funkcionalnosti postavljano glana tema u toku I meseca u taj peju 2007 godine.

fleurs_1941_sr.wav | WER=66.67%
REF: ovi parovi mogu da odluče da isplaniraju usvajanje bebe
HYP: Ove para joj mogu da odluči da isplaniraju svanja... babe

fleurs_1807_sr.wav | WER=66.67%
REF: italijanski je takođe svakodnevni jezik koji koristi većina onih koji rade u državi dok se latinski često koristi u religijskim obredima
HYP: i talijenski otak ovdje svaku na mnije zika koji koristi već o njih koji radi u državi dok se latinski često koristi u religijski...

fleurs_1810_sr.wav | WER=61.11%
REF: guverner kalifornije arnold švarceneger potpisom je učinio punovažnim zakon koji zabranjuje prodaju ili iznajmljivanje nasilnih video-igrica maloletnicima
HYP: Governor Kalifornije Arnold Schwarzenegger, podpisom je učinio punova... koji zabranju je prodaju ili iznajnjevanje nasilnih video igricama u letnici.

fleurs_1829_sr.wav | WER=58.33%
REF: putnici koji idu u zemlje sa visokim porezima mogu ponekad uštedeti prilične sume novca naročito na proizvodima kao što su alkoholna pića i duvan
HYP: Putnici koji idu u zemlje sa visokim porazima modu lupone nekada ušte sumenovoca naročite na proizvodima kašto su alkohol na piće i dup.

fleurs_1845_sr.wav | WER=57.89%
REF: putovali su natrag u pariz kočijom okruženi ruljom ljudi koji su vrištali i uzvikivali pretnje upućene kralju i kraljici
HYP: Putovali su natragupari s Korčijom, okruženim žuljom u rdiku. koji su vrištali i uzvikevali pretni upućene kraju i kraljeci.

fleurs_1687_sr.wav | WER=57.14%
REF: segregacija i rekombinovanje utiču na stalno mešanje varijacija između dva fonda u svakoj generaciji
HYP: Segregacija i rekombinovanje utiču na stavno mešanje variac Značite imu življenu. fondosvaku i generati.

fleurs_1983_sr.wav | WER=57.14%
REF: reč civilizacija potiče od latinske reči civilis što znači građanski a povezano je sa latinskim civis što znači građanin i civitas što znači grad ili grad-država a to isto nekako definiše i veličinu zajednice
HYP: Rečcivilizacija potiče od datenske reći cibilis. znači građanske, a povezano je sa latenskim civis i civites, znaći grad ili grad država. definiši je veličinu zajednice

## Završna evaluacija na 40 prirodnih srpskih snimaka — dva načina obrade

**Cilj:** ispitati *isti integrisani profil iz 08* na originalnom skupu od 40 snimaka iz eksperimenta 05, u dva načina rada: (1) odabrani streaming režim sa preklapanjem/kontekstom prema profilu i (2) obrada celog snimka bez streaming segmentacije. Oba rezultata su važna: prvi ispituje ponašanje sistema u streaming simulaciji, drugi je kontrolni *batch baseline*. **Bez batch poređenja nije moguće pripisati promenu WER-a samoj segmentaciji.**

**Ograničenje:** ovi snimci su već učestvovali u izboru veličine modela i kvantizacije u 08; rezultati predstavljaju *evaluaciju na razvojnom benchmark-u*, a ne nezavisnu test validaciju. FLEURS poređenje iznad ostaje kao dodatna međukorpusna provera. Rezultati dva korpusa ne spajaju se u jedinstveni corpus WER.

Izvor referenci: originalni rečnik `REFERENCE` iz skripte 08 (40 rečenica). Audio: `audio/40Sentences00-08Notebooks/`. VAD i ostali parametri ostaju kao u profilu iz 08.

In [15]:
# Originalne reference iz 08, bez generisanja ili zamene ASR hipotezama.
REFERENCE_40 = {1: 'Veštačka inteligencija omogućava računarima da rešavaju složene probleme i analiziraju velike količine podataka.', 2: 'Automatsko prepoznavanje govora pretvara izgovorene reči u tekst koji računar može dalje da obrađuje.', 3: 'Danas je veoma prijatan dan, pa smo odlučili da prošetamo kroz centar grada posle ručka.', 4: 'Novi računari imaju brže procesore, više memorije i znatno bolje performanse nego prethodne generacije.', 5: 'Mašinsko učenje koristi podatke kako bi model naučio da prepoznaje obrasce i donosi odgovarajuće odluke.', 6: 'Sutra ujutru moram da završim nekoliko obaveza, a zatim planiram da se vidim sa prijateljima.', 7: 'Kvalitet zvučnog zapisa može značajno da utiče na tačnost sistema za automatsko prepoznavanje govora.', 8: 'Temperatura je tokom noći naglo pala, ali se očekuje da će sutra vreme ponovo biti toplije.', 9: 'Neuronske mreže danas se koriste za obradu slike, teksta, zvuka i mnogih drugih vrsta podataka.', 10: 'Dobar sistem mora istovremeno da bude dovoljno brz, precizan i pouzdan u različitim uslovima.', 11: 'Savremeni sistemi za automatsko prepoznavanje govora koriste duboke neuronske mreže kako bi analizirali zvučni signal i pretvorili ga u tekst. Njihova tačnost zavisi od modela, kvaliteta snimka, jezika i karakteristika govornika.', 12: 'Juče sam krenuo do grada nešto ranije nego obično. Na ulicama nije bilo mnogo ljudi, pa sam brzo završio sve obaveze. Nakon toga sam seo u obližnji kafić i sačekao prijatelja.', 13: 'Whisper je model za automatsko prepoznavanje govora koji može da radi sa velikim brojem jezika. Faster-Whisper koristi optimizovanu implementaciju koja omogućava efikasnije izvršavanje i manju potrošnju računarskih resursa.', 14: 'Kada razgovaramo u tihoj prostoriji, sistem uglavnom može veoma jasno da prepozna izgovorene reči. Međutim, saobraćaj, muzika, razgovor drugih ljudi i različiti izvori šuma mogu značajno da otežaju transkripciju.', 15: 'Tokom razvoja softverske aplikacije programeri prvo analiziraju zahteve korisnika, zatim projektuju sistem i implementiraju potrebne funkcionalnosti. Nakon toga slede testiranje, ispravljanje grešaka i postavljanje aplikacije u produkciono okruženje.', 16: 'Prošlog vikenda smo odlučili da provedemo dan u prirodi. Vreme je bilo sunčano i prijatno, pa smo poneli hranu i nekoliko stvari koje su nam bile potrebne. Vratili smo se kući tek predveče.', 17: 'Veći modeli mašinskog učenja često mogu da postignu veću tačnost, ali zahtevaju više memorije i procesorske snage. Zbog toga najveći model nije uvek najbolji izbor za praktičnu primenu.', 18: 'Brzina automatskog prepoznavanja govora posebno je važna kod aplikacija koje rade u realnom vremenu. Korisnik očekuje da sistem reaguje brzo i da se transkript pojavljuje bez primetnog kašnjenja.', 19: 'Kada sam jutros uključio računar, prvo sam proverio elektronsku poštu i poruke. Posle toga sam otvorio projekat na kojem trenutno radim i nastavio implementaciju funkcionalnosti koju sam započeo prethodnog dana.', 20: 'Srpski jezik sadrži glasove i karaktere koji se razlikuju od engleskog jezika. Zbog toga je interesantno analizirati koliko dobro isti model prepoznaje govor na različitim jezicima.', 21: 'Kvantizacija omogućava da se neuronski model izvršava korišćenjem manje preciznih numeričkih formata. Na taj način moguće je smanjiti potrošnju memorije i ubrzati izvršavanje uz prihvatljivu promenu tačnosti.', 22: 'Čovek tokom običnog razgovora često pravi kratke pauze, menja brzinu govora ili zastane kako bi razmislio. Sistem za prepoznavanje govora mora da bude dovoljno robustan da pravilno obradi takve situacije.', 23: 'Danas postoji veliki broj aplikacija koje koriste veštačku inteligenciju. Ona se primenjuje u medicini, industriji, obrazovanju, saobraćaju, finansijama i mnogim svakodnevnim digitalnim servisima.', 24: 'Kada se zvučnom signalu doda šum, neke reči postaju teže razumljive. Što je nivo šuma veći u odnosu na govor, sistemu je teže da napravi tačnu transkripciju celog snimka.', 25: 'Pre nego što rezultate eksperimenta možemo pravilno da uporedimo, potrebno je koristiti iste ulazne podatke i jasno definisane metrike. Na taj način razlika u rezultatima može da se poveže sa promenom koju zapravo ispitujemo.', 26: 'Automatsko prepoznavanje govora predstavlja oblast veštačke inteligencije koja se bavi pretvaranjem zvučnog signala u tekst. Savremeni sistemi koriste modele dubokog učenja koji mogu da analiziraju kompleksne karakteristike ljudskog govora. Njihove performanse mogu da zavise od jezika, kvaliteta mikrofona, prisustva pozadinskog šuma, brzine govora i karakteristika samog govornika. Zbog toga je prilikom evaluacije važno koristiti različite vrste zvučnih zapisa.', 27: 'Jednog jutra krenuo sam automobilom prema gradu nešto ranije nego obično. Saobraćaj je u početku bio veoma slab, ali se približavanjem centru broj vozila postepeno povećavao. Dok sam čekao na semaforu, na radiju su govorili o vremenskoj prognozi za narednih nekoliko dana. Najavljeno je sunčano vreme, ali i mogućnost kratkotrajne kiše tokom vikenda. Kada sam stigao, parkirao sam automobil i nastavio pešice.', 28: 'Whisper postoji u više veličina modela, od veoma malih do znatno većih modela. Manji modeli zahtevaju manje memorije i uglavnom omogućavaju bržu transkripciju, dok veći modeli mogu da pruže veću tačnost u zahtevnijim uslovima. Zbog toga izbor modela predstavlja kompromis između kvaliteta transkripcije i potrebnih računarskih resursa. Taj kompromis je posebno važan kada se sistem izvršava na običnom računaru bez snažne grafičke kartice.', 29: 'Pozadinski šum predstavlja jedan od najčešćih problema kod sistema za automatsko prepoznavanje govora. U realnom okruženju mikrofon ne snima samo glas osobe već i zvuk automobila, ventilatora, drugih ljudi ili muzike. Ako je govor dovoljno snažan u odnosu na šum, transkripcija može ostati veoma dobra. Međutim, kada se odnos signala i šuma smanjuje, broj pogrešno prepoznatih reči uglavnom počinje da raste.', 30: 'Kada razvijamo sistem koji treba da radi u realnom vremenu, nije dovoljno posmatrati samo njegovu tačnost. Potrebno je analizirati koliko vremena modelu treba da obradi određenu količinu zvuka. Ako obrada pet sekundi govora traje kraće od pet sekundi, sistem potencijalno može da prati govor bez stalnog povećavanja kašnjenja. Zbog toga su latencija i faktor realnog vremena veoma korisne metrike prilikom evaluacije ovakvih sistema.', 31: 'Pre nekoliko dana organizovali smo malo okupljanje sa prijateljima. Dogovor je bio da se svi nađemo oko šest sati, ali je nekoliko ljudi kasnilo zbog saobraćaja. Dok smo ih čekali, razgovarali smo o poslu, putovanjima i planovima za naredne mesece. Kasnije smo naručili večeru i ostali zajedno nekoliko sati. Iako ništa posebno nije bilo planirano, veče je na kraju bilo veoma zanimljivo i prijatno.', 32: 'Ljudski govor nije potpuno konstantan signal. Neko govori brzo, neko sporije, a pojedini govornici prave veoma duge pauze između rečenica. Razlikuju se i visina glasa, naglasak, način izgovora i jačina govora. Sistem koji postiže odlične rezultate kod jednog govornika zato ne mora nužno da postigne iste rezultate kod druge osobe. Korišćenje više govornika omogućava realniju procenu sposobnosti modela da generalizuje.', 33: 'Voice Activity Detection koristi se za razlikovanje delova zvučnog zapisa u kojima postoji govor od delova u kojima se nalazi tišina. Ako snimak sadrži duge periode bez govora, njihovo uklanjanje može da smanji količinu podataka koju model mora da obradi. Međutim, algoritam mora pažljivo da odredi početak i kraj govora, jer previše agresivno uklanjanje može da odseče deo izgovorene reči i tako negativno utiče na transkripciju.', 34: 'Beam search predstavlja jedan od načina pronalaženja verovatne sekvence reči tokom dekodiranja rezultata modela. Veća vrednost parametra omogućava razmatranje većeg broja mogućih kandidata, ali istovremeno može da poveća vreme potrebno za obradu. Zbog toga je korisno eksperimentalno proveriti da li povećanje beam size parametra zaista donosi značajno poboljšanje tačnosti i koliko dodatnih računarskih resursa zahteva.', 35: 'Prilikom izvođenja eksperimenta veoma je važno menjati jednu karakteristiku sistema dok ostali uslovi ostaju isti. Ako istovremeno promenimo model, jezik, kvalitet zvuka i parametre dekodiranja, teško možemo da zaključimo zbog čega je rezultat postao bolji ili lošiji. Kontrolisani eksperimenti omogućavaju jasnije poređenje različitih konfiguracija i daju pouzdaniju osnovu za izvođenje zaključaka o ponašanju sistema.', 36: 'Savremeni sistemi za automatsko prepoznavanje govora imaju veliki broj praktičnih primena. Mogu se koristiti za automatsko pravljenje transkripata sastanaka, generisanje titlova, glasovne asistente, pretragu multimedijalnog sadržaja i poboljšanje pristupačnosti digitalnih sistema. Ipak, kvalitet njihovog rada zavisi od velikog broja faktora. Govornici imaju različite glasove, akcente i brzine govora, dok snimci mogu nastati korišćenjem različitih mikrofona i u različitim prostorijama. Dodatni problem predstavlja pozadinski šum. Sistem koji veoma dobro radi u tihoj prostoriji ne mora da postigne isti rezultat na ulici ili u automobilu. Zbog toga evaluacija sistema ne bi trebalo da bude zasnovana na samo jednom zvučnom zapisu. Potrebno je koristiti više govornika, različite dužine snimaka i različite uslove. Pored tačnosti transkripcije, važno je analizirati vreme izvršavanja, potrošnju memorije i sposobnost sistema da obrađuje zvuk dovoljno brzo za praktičnu primenu.', 37: 'Kada govorimo o performansama modela za prepoznavanje govora, postoje dve različite stvari koje želimo da postignemo. Prva je što tačniji transkript, a druga što efikasnije izvršavanje. Veći model može bolje da prepozna komplikovane rečenice ili govor u težim uslovima, ali istovremeno može zahtevati mnogo više memorije i vremena. Manji model može biti nešto manje precizan, ali dovoljno brz da se koristi na običnom laptopu. Kvantizacija predstavlja još jedan način optimizacije jer omogućava korišćenje numeričkog formata manje preciznosti. Time se može smanjiti količina potrebne memorije i ubrzati obrada. Međutim, svaka optimizacija mora da bude eksperimentalno proverena. Nije dovoljno pokazati da je jedna konfiguracija brža. Potrebno je proveriti i da li je njena tačnost ostala prihvatljiva. Upravo zato se koriste metrike kao što su Word Error Rate, latencija i Real-Time Factor, koje omogućavaju da različite konfiguracije modela budu upoređene na objektivan način.', 38: 'Prošle nedelje imao sam prilično ispunjen dan. Ujutru sam ustao ranije jer sam morao da završim nekoliko obaveza pre odlaska u grad. Posle doručka proverio sam poruke, pripremio stvari koje su mi bile potrebne i krenuo automobilom. Na putu je bilo više saobraćaja nego što sam očekivao, pa mi je trebalo skoro pola sata da stignem do centra. Prvo sam otišao do prodavnice, zatim do banke, a nakon toga sam se našao sa prijateljem kojeg nisam video nekoliko meseci. Razgovarali smo o poslu, putovanjima i planovima za narednu godinu. Posle ručka vreme se iznenada promenilo i počela je jaka kiša. Sačekali smo nekoliko minuta da se vreme malo smiri, a onda smo krenuli kući. Kada sam se vratio, nastavio sam da radim na računaru. Uveče sam završio preostale obaveze i odlučio da ostatak dana provedem odmarajući se.', 39: 'Sistem koji obrađuje govor u realnom vremenu mora da rešava nešto drugačiji problem od sistema koji dobije kompletan audio zapis. Kod klasične transkripcije model može da dobije čitav snimak i zatim ga obradi. Kod realnog vremena zvuk neprestano pristiže, pa ga je potrebno podeliti na manje delove. Ako koristimo veoma kratke segmente, sistem može brzo da prikaže rezultat, ali model ima manje konteksta za pravilno prepoznavanje rečenice. Sa druge strane, ako koristimo duge segmente, model dobija više konteksta, ali korisnik mora duže da čeka na rezultat. Zbog toga izbor veličine segmenta predstavlja kompromis između latencije i kvaliteta transkripcije. Na primer, mogu se uporediti segmenti od dve, pet i deset sekundi. Za svaku konfiguraciju moguće je izmeriti vreme obrade, faktor realnog vremena i tačnost konačnog transkripta. Takav eksperiment omogućava da se utvrdi koja konfiguracija predstavlja najbolji kompromis za praktičan sistem.', 40: 'Cilj eksperimentalne analize sistema za automatsko prepoznavanje govora jeste da se utvrdi kako različiti faktori utiču na njegov rad. Možemo menjati veličinu modela, nivo pozadinskog šuma, jezik govornika, parametre dekodiranja, način kvantizacije ili korišćenje algoritma za detekciju govora. Svaki eksperiment treba organizovati tako da možemo jasno da utvrdimo posledice određene promene. Rezultati se zatim mogu posmatrati kroz više metrika. Word Error Rate pokazuje koliko se prepoznati tekst razlikuje od tačnog referentnog transkripta. Latencija pokazuje koliko vremena je potrebno za obradu, dok Real-Time Factor povezuje vreme obrade sa trajanjem samog zvučnog zapisa. Potrošnja memorije je posebno značajna kada model treba da radi na uređajima sa ograničenim resursima. Kombinovanjem ovih rezultata možemo da pronađemo konfiguraciju koja ne mora biti najbolja prema svakoj pojedinačnoj metrici, ali predstavlja dobar kompromis između tačnosti, brzine i potrebnih računarskih resursa.'}

AUDIO_40_DIR = PROJECT_ROOT / 'audio' / '40Sentences00-08Notebooks'
REZULTATI_40_DIR = PROJECT_ROOT / 'rezultati' / '99_validacija_40_prirodnih'
REZULTATI_40_DIR.mkdir(parents=True, exist_ok=True)

def govornik_40(broj):
    if broj in set(range(1,5)) | set(range(11,16)) | set(range(26,29)) | {36}:
        return 'govornik1'
    if broj in set(range(5,8)) | set(range(16,21)) | set(range(29,32)) | {37,38}:
        return 'govornik2'
    return 'govornik3'

def grupa_40(broj):
    if broj <= 10: return 'kratki'
    if broj <= 25: return 'srednji'
    if broj <= 35: return 'dugi'
    return 'veoma_dugi'

test_set_40 = []
for broj in range(1, 41):
    govornik = govornik_40(broj)
    putanja = AUDIO_40_DIR / f'{broj}{govornik}.wav'
    if not putanja.is_file():
        raise FileNotFoundError(f'Nedostaje WAV {broj}/40: {putanja}')
    ref = REFERENCE_40.get(broj, '').strip()
    if not ref:
        raise ValueError(f'Nedostaje originalna referenca za snimak {broj}')
    test_set_40.append(dict(broj=broj, audio=str(putanja), ref=ref,
                            govornik=govornik, grupa=grupa_40(broj)))
assert len(test_set_40) == 40 and len({x['broj'] for x in test_set_40}) == 40
pd.DataFrame(test_set_40).to_csv(REZULTATI_40_DIR / '99_40_reference_i_putanje.csv', index=False, encoding='utf-8-sig')
print('Potvrđeno 40 WAV datoteka i 40 originalnih referenci.')

Potvrđeno 40 WAV datoteka i 40 originalnih referenci.

### Streaming: izabrani integrisani profil na svih 40 snimaka

Ne menja se nijedan parametar na osnovu rezultata. Koristi se ista funkcija `transkribuj_u_chunkovima` kao na FLEURS skupu. TTFR je simulirano vreme od početka audio toka do prvog delimičnog rezultata; nije stvarno izmeren mikrofonски streaming.

In [16]:
rezultati_40_stream, chunkovi_40 = [], []
for i, item in enumerate(test_set_40, 1):
    putanja = Path(item['audio'])
    audio, sr = ucitaj_wav_pcm16(putanja)
    audio = resampluj_na_16k(audio, sr)
    trajanje = len(audio) / WHISPER_SAMPLE_RATE
    if trajanje <= 0: raise ValueError(f'Prazan WAV: {putanja}')
    t0 = time.perf_counter()
    hyp, rows, m = transkribuj_u_chunkovima(model, audio)
    wall = time.perf_counter() - t0
    z = process_words(normalizuj_tekst(item['ref']), normalizuj_tekst(hyp))
    nref = z.substitutions + z.deletions + z.hits
    if not nref: raise ValueError(f'Prazna normalizovana referenca: {putanja}')
    rezultati_40_stream.append(dict(Broj=item['broj'], Fajl=putanja.name,
        Govornik=item['govornik'], Grupa=item['grupa'], Model=MODEL_SIZE,
        Kvantizacija=COMPUTE_TYPE, Beam_size=BEAM_SIZE, VAD=VAD_FILTER,
        Rezim=REZIM, Chunk_s=CHUNK_SECONDS, Overlap_s=OVERLAP_SEC,
        Prompt_max_reci=PROMPT_MAX_RECI, Trajanje_s=trajanje,
        Broj_chunkova=len(rows), Referenca=item['ref'], Transkript=hyp,
        WER_pct=100*(z.substitutions+z.deletions+z.insertions)/nref,
        Zamene=z.substitutions, Brisanja=z.deletions, Umetanja=z.insertions,
        Referentne_reci=nref, Vreme_s=wall, RTF=wall/trajanje,
        RTF_inference=m['Ukupno_inference_s']/trajanje, **m))
    chunkovi_40.extend(dict(Broj=item['broj'], Fajl=putanja.name,
        Rezim=REZIM, Chunk_s=CHUNK_SECONDS, **r) for r in rows)
    print(f'[STREAM {i:02d}/40] {putanja.name}: WER={rezultati_40_stream[-1]["WER_pct"]:.2f}% RTF={wall/trajanje:.3f} TTFR={m["TTFR_s"]:.2f}s')

df_40_stream = pd.DataFrame(rezultati_40_stream)
df_40_chunks = pd.DataFrame(chunkovi_40)
assert len(df_40_stream)==40 and df_40_stream.Broj.nunique()==40
df_40_stream.to_csv(REZULTATI_40_DIR / '99_40_streaming_po_snimku.csv', index=False, encoding='utf-8-sig')
df_40_chunks.to_csv(REZULTATI_40_DIR / '99_40_streaming_chunkovi.csv', index=False, encoding='utf-8-sig')
display(df_40_stream[['Broj','Fajl','Grupa','WER_pct','RTF','TTFR_s','Broj_chunkova']].round(3))

[STREAM 01/40] 1govornik1.wav: WER=46.15% RTF=1.401 TTFR=12.10s
[STREAM 02/40] 2govornik1.wav: WER=28.57% RTF=1.799 TTFR=12.86s
[STREAM 03/40] 3govornik1.wav: WER=26.67% RTF=2.054 TTFR=13.11s
[STREAM 04/40] 4govornik1.wav: WER=28.57% RTF=1.658 TTFR=13.24s
[STREAM 05/40] 5govornik2.wav: WER=20.00% RTF=1.075 TTFR=11.46s
[STREAM 06/40] 6govornik2.wav: WER=26.67% RTF=1.502 TTFR=13.07s
[STREAM 07/40] 7govornik2.wav: WER=28.57% RTF=1.497 TTFR=13.43s
[STREAM 08/40] 8govornik3.wav: WER=25.00% RTF=2.383 TTFR=13.30s
[STREAM 09/40] 9govornik3.wav: WER=66.67% RTF=2.399 TTFR=13.43s
[STREAM 10/40] 10govornik3.wav: WER=28.57% RTF=2.127 TTFR=13.09s
[STREAM 11/40] 11govornik1.wav: WER=32.26% RTF=1.345 TTFR=12.15s
[STREAM 12/40] 12govornik1.wav: WER=45.16% RTF=1.321 TTFR=13.14s
[STREAM 13/40] 13govornik1.wav: WER=34.48% RTF=1.386 TTFR=12.51s
[STREAM 14/40] 14govornik1.wav: WER=58.62% RTF=1.411 TTFR=12.87s
[STREAM 15/40] 15govornik1.wav: WER=57.14% RTF=1.212 TTFR=12.80s
[STREAM 16/40] 16govornik2.wav: WER=27.27% RTF=1.025 TTFR=9.44s
[STREAM 17/40] 17govornik2.wav: WER=10.71% RTF=1.317 TTFR=13.56s
[STREAM 18/40] 18govornik2.wav: WER=21.43% RTF=0.986 TTFR=9.78s
[STREAM 19/40] 19govornik2.wav: WER=36.67% RTF=1.257 TTFR=11.83s
[STREAM 20/40] 20govornik2.wav: WER=19.23% RTF=1.021 TTFR=9.19s
[STREAM 21/40] 21govornik3.wav: WER=55.56% RTF=1.099 TTFR=11.59s
[STREAM 22/40] 22govornik3.wav: WER=30.00% RTF=1.207 TTFR=13.26s
[STREAM 23/40] 23govornik3.wav: WER=56.52% RTF=1.734 TTFR=13.28s
[STREAM 24/40] 24govornik3.wav: WER=41.38% RTF=1.581 TTFR=13.62s
[STREAM 25/40] 25govornik3.wav: WER=35.29% RTF=1.597 TTFR=13.53s
[STREAM 26/40] 26govornik1.wav: WER=34.48% RTF=1.232 TTFR=13.70s
[STREAM 27/40] 27govornik1.wav: WER=33.87% RTF=1.212 TTFR=12.95s
[STREAM 28/40] 28govornik1.wav: WER=36.51% RTF=1.308 TTFR=13.19s
[STREAM 29/40] 29govornik2.wav: WER=31.15% RTF=1.188 TTFR=13.41s
[STREAM 30/40] 30govornik2.wav: WER=12.70% RTF=1.073 TTFR=12.89s
[STREAM 31/40] 31govornik2.wav: WER=20.31% RTF=1.080 TTFR=13.77s
[STREAM 32/40] 32govornik3.wav: WER=43.33% RTF=1.394 TTFR=13.17s
[STREAM 33/40] 33govornik3.wav: WER=43.94% RTF=1.123 TTFR=8.99s
[STREAM 34/40] 34govornik3.wav: WER=49.09% RTF=1.094 TTFR=12.99s
[STREAM 35/40] 35govornik3.wav: WER=42.59% RTF=1.291 TTFR=13.02s
[STREAM 36/40] 36govornik1.wav: WER=40.77% RTF=1.023 TTFR=13.45s
[STREAM 37/40] 37govornik2.wav: WER=21.99% RTF=0.858 TTFR=8.79s
[STREAM 38/40] 38govornik2.wav: WER=24.82% RTF=1.020 TTFR=11.93s
[STREAM 39/40] 39govornik3.wav: WER=44.60% RTF=1.135 TTFR=13.02s
[STREAM 40/40] 40govornik3.wav: WER=32.84% RTF=0.898 TTFR=11.47s

    Broj             Fajl       Grupa  WER_pct    RTF  TTFR_s  Broj_chunkova
0      1   1govornik1.wav      kratki   46.154  1.401  12.099              2
1      2   2govornik1.wav      kratki   28.571  1.799  12.855              2
2      3   3govornik1.wav      kratki   26.667  2.054  13.114              2
3      4   4govornik1.wav      kratki   28.571  1.658  13.239              2
4      5   5govornik2.wav      kratki   20.000  1.075  11.461              2
5      6   6govornik2.wav      kratki   26.667  1.502  13.072              2
6      7   7govornik2.wav      kratki   28.571  1.497  13.435              2
7      8   8govornik3.wav      kratki   25.000  2.383  13.303              2
8      9   9govornik3.wav      kratki   66.667  2.399  13.432              2
9     10  10govornik3.wav      kratki   28.571  2.127  13.088              2
10    11  11govornik1.wav     srednji   32.258  1.345  12.147              4
11    12  12govornik1.wav     srednji   45.161  1.321  13.139              3
12    13  13govornik1.wav     srednji   34.483  1.386  12.515              4
13    14  14govornik1.wav     srednji   58.621  1.411  12.872              4
14    15  15govornik1.wav     srednji   57.143  1.212  12.798              4
15    16  16govornik2.wav     srednji   27.273  1.025   9.443              4
16    17  17govornik2.wav     srednji   10.714  1.317  13.564              4
17    18  18govornik2.wav     srednji   21.429  0.986   9.781              4
18    19  19govornik2.wav     srednji   36.667  1.257  11.829              4
19    20  20govornik2.wav     srednji   19.231  1.021   9.190              4
20    21  21govornik3.wav     srednji   55.556  1.099  11.595              3
21    22  22govornik3.wav     srednji   30.000  1.207  13.260              3
22    23  23govornik3.wav     srednji   56.522  1.734  13.282              3
23    24  24govornik3.wav     srednji   41.379  1.581  13.620              3
24    25  25govornik3.wav     srednji   35.294  1.597  13.527              3
25    26  26govornik1.wav        dugi   34.483  1.232  13.702              7
26    27  27govornik1.wav        dugi   33.871  1.212  12.945              6
27    28  28govornik1.wav        dugi   36.508  1.308  13.188              7
28    29  29govornik2.wav        dugi   31.148  1.188  13.407              7
29    30  30govornik2.wav        dugi   12.698  1.073  12.890              8
30    31  31govornik2.wav        dugi   20.312  1.080  13.774              7
31    32  32govornik3.wav        dugi   43.333  1.394  13.169              6
32    33  33govornik3.wav        dugi   43.939  1.123   8.994              7
33    34  34govornik3.wav        dugi   49.091  1.094  12.985              7
34    35  35govornik3.wav        dugi   42.593  1.291  13.022              6
35    36  36govornik1.wav  veoma_dugi   40.769  1.023  13.455             14
36    37  37govornik2.wav  veoma_dugi   21.986  0.858   8.792             17
37    38  38govornik2.wav  veoma_dugi   24.818  1.020  11.935             13
38    39  39govornik3.wav  veoma_dugi   44.604  1.135  13.023             13
39    40  40govornik3.wav  veoma_dugi   32.836  0.898  11.470             16

### Kontrolni test: isti model na celim snimcima

Jedan poziv po WAV datoteci, bez streaming segmentacije, preklapanja i `initial_prompt`. To **nije** alternativni izbor konfiguracije, već neophodan kontrolni uslov. Vreme do batch rezultata definisano je kao trajanje snimka + vreme dekodiranja (simulacija da je ceo snimak prvo pristigao).

In [20]:
rezultati_40_ceo = []
for i, item in enumerate(test_set_40, 1):
    putanja = Path(item['audio'])
    audio, sr = ucitaj_wav_pcm16(putanja)
    audio = resampluj_na_16k(audio, sr)
    trajanje = len(audio) / WHISPER_SAMPLE_RATE
    if trajanje <= 0: raise ValueError(f'Prazan WAV: {putanja}')
    t0 = time.perf_counter()
    hyp, inference_s = transkribuj_ceo_snimak(model, audio)
    wall = time.perf_counter() - t0
    z = process_words(normalizuj_tekst(item['ref']), normalizuj_tekst(hyp))
    nref = z.substitutions + z.deletions + z.hits
    if not nref: raise ValueError(f'Prazna referenca: {putanja}')
    rezultati_40_ceo.append(dict(Broj=item['broj'], Fajl=putanja.name,
        Govornik=item['govornik'], Grupa=item['grupa'], Model=MODEL_SIZE,
        Kvantizacija=COMPUTE_TYPE, Beam_size=BEAM_SIZE, VAD=VAD_FILTER,
        Rezim='CEO_SNIMAK_BEZ_SEGMENTACIJE', Chunk_s=np.nan,
        Overlap_s=0., Prompt_max_reci=0, Trajanje_s=trajanje,
        Broj_chunkova=1, Referenca=item['ref'], Transkript=hyp,
        WER_pct=100*(z.substitutions+z.deletions+z.insertions)/nref,
        Zamene=z.substitutions, Brisanja=z.deletions, Umetanja=z.insertions,
        Referentne_reci=nref, Vreme_s=wall, RTF=wall/trajanje,
        RTF_inference=inference_s/trajanje, Ukupno_inference_s=inference_s,
        TTFR_s=trajanje+inference_s, Max_queue_s=np.nan,
        Max_result_delay_s=np.nan, Final_tail_s=inference_s))
    print(f'[CEO {i:02d}/40] {putanja.name}: WER={rezultati_40_ceo[-1]["WER_pct"]:.2f}% RTF={wall/trajanje:.3f}')

df_40_ceo = pd.DataFrame(rezultati_40_ceo)
assert len(df_40_ceo)==40 and df_40_ceo.Broj.nunique()==40
df_40_ceo.to_csv(REZULTATI_40_DIR / '99_40_ceo_snimak_po_snimku.csv', index=False, encoding='utf-8-sig')
display(df_40_ceo[['Broj','Fajl','Grupa','WER_pct','RTF','TTFR_s']].round(3))

[CEO 01/40] 1govornik1.wav: WER=15.38% RTF=0.499
[CEO 02/40] 2govornik1.wav: WER=7.14% RTF=0.528
[CEO 03/40] 3govornik1.wav: WER=20.00% RTF=0.554
[CEO 04/40] 4govornik1.wav: WER=21.43% RTF=0.509
[CEO 05/40] 5govornik2.wav: WER=13.33% RTF=0.439
[CEO 06/40] 6govornik2.wav: WER=13.33% RTF=0.516
[CEO 07/40] 7govornik2.wav: WER=14.29% RTF=0.472
[CEO 08/40] 8govornik3.wav: WER=12.50% RTF=0.740
[CEO 09/40] 9govornik3.wav: WER=26.67% RTF=0.753
[CEO 10/40] 10govornik3.wav: WER=28.57% RTF=0.696
[CEO 11/40] 11govornik1.wav: WER=19.35% RTF=0.369
[CEO 12/40] 12govornik1.wav: WER=29.03% RTF=0.464
[CEO 13/40] 13govornik1.wav: WER=31.03% RTF=0.416
[CEO 14/40] 14govornik1.wav: WER=27.59% RTF=0.410
[CEO 15/40] 15govornik1.wav: WER=35.71% RTF=0.372
[CEO 16/40] 16govornik2.wav: WER=12.12% RTF=0.322
[CEO 17/40] 17govornik2.wav: WER=3.57% RTF=0.345
[CEO 18/40] 18govornik2.wav: WER=10.71% RTF=0.313
[CEO 19/40] 19govornik2.wav: WER=16.67% RTF=0.351
[CEO 20/40] 20govornik2.wav: WER=15.38% RTF=0.340
[CEO 21/40] 21govornik3.wav: WER=37.04% RTF=0.442
[CEO 22/40] 22govornik3.wav: WER=16.67% RTF=0.426
[CEO 23/40] 23govornik3.wav: WER=34.78% RTF=0.475
[CEO 24/40] 24govornik3.wav: WER=27.59% RTF=0.448
[CEO 25/40] 25govornik3.wav: WER=23.53% RTF=0.434
[CEO 26/40] 26govornik1.wav: WER=24.14% RTF=0.434
[CEO 27/40] 27govornik1.wav: WER=17.74% RTF=0.415
[CEO 28/40] 28govornik1.wav: WER=28.57% RTF=0.471
[CEO 29/40] 29govornik2.wav: WER=19.67% RTF=0.352
[CEO 30/40] 30govornik2.wav: WER=7.94% RTF=0.337
[CEO 31/40] 31govornik2.wav: WER=9.38% RTF=0.345
[CEO 32/40] 32govornik3.wav: WER=45.00% RTF=0.407
[CEO 33/40] 33govornik3.wav: WER=39.39% RTF=0.392
[CEO 34/40] 34govornik3.wav: WER=50.91% RTF=0.387
[CEO 35/40] 35govornik3.wav: WER=33.33% RTF=0.424
[CEO 36/40] 36govornik1.wav: WER=31.54% RTF=0.362
[CEO 37/40] 37govornik2.wav: WER=8.51% RTF=0.352
[CEO 38/40] 38govornik2.wav: WER=8.03% RTF=0.348
[CEO 39/40] 39govornik3.wav: WER=30.94% RTF=0.422
[CEO 40/40] 40govornik3.wav: WER=29.10% RTF=0.299

    Broj             Fajl       Grupa  WER_pct    RTF   TTFR_s
0      1   1govornik1.wav      kratki   15.385  0.499   11.396
1      2   2govornik1.wav      kratki    7.143  0.528   10.361
2      3   3govornik1.wav      kratki   20.000  0.554    9.059
3      4   4govornik1.wav      kratki   21.429  0.509   11.000
4      5   5govornik2.wav      kratki   13.333  0.439   13.428
5      6   6govornik2.wav      kratki   13.333  0.516   11.968
6      7   7govornik2.wav      kratki   14.286  0.472   12.854
7      8   8govornik3.wav      kratki   12.500  0.740    9.069
8      9   9govornik3.wav      kratki   26.667  0.753    9.364
9     10  10govornik3.wav      kratki   28.571  0.696    9.489
10    11  11govornik1.wav     srednji   19.355  0.369   22.535
11    12  12govornik1.wav     srednji   29.032  0.464   18.626
12    13  13govornik1.wav     srednji   31.034  0.416   21.356
13    14  14govornik1.wav     srednji   27.586  0.410   21.994
14    15  15govornik1.wav     srednji   35.714  0.372   23.907
15    16  16govornik2.wav     srednji   12.121  0.322   23.325
16    17  17govornik2.wav     srednji    3.571  0.345   22.303
17    18  18govornik2.wav     srednji   10.714  0.313   23.899
18    19  19govornik2.wav     srednji   16.667  0.351   22.837
19    20  20govornik2.wav     srednji   15.385  0.340   21.724
20    21  21govornik3.wav     srednji   37.037  0.442   21.014
21    22  22govornik3.wav     srednji   16.667  0.426   20.893
22    23  23govornik3.wav     srednji   34.783  0.475   18.014
23    24  24govornik3.wav     srednji   27.586  0.448   16.860
24    25  25govornik3.wav     srednji   23.529  0.434   20.504
25    26  26govornik1.wav        dugi   24.138  0.434   44.592
26    27  27govornik1.wav        dugi   17.742  0.415   38.852
27    28  28govornik1.wav        dugi   28.571  0.471   45.159
28    29  29govornik2.wav        dugi   19.672  0.352   47.272
29    30  30govornik2.wav        dugi    7.937  0.337   50.477
30    31  31govornik2.wav        dugi    9.375  0.345   47.031
31    32  32govornik3.wav        dugi   45.000  0.407   39.341
32    33  33govornik3.wav        dugi   39.394  0.392   43.504
33    34  34govornik3.wav        dugi   50.909  0.387   45.884
34    35  35govornik3.wav        dugi   33.333  0.424   41.380
35    36  36govornik1.wav  veoma_dugi   31.538  0.362   93.991
36    37  37govornik2.wav  veoma_dugi    8.511  0.352  111.414
37    38  38govornik2.wav  veoma_dugi    8.029  0.348   86.865
38    39  39govornik3.wav  veoma_dugi   30.935  0.422   89.007
39    40  40govornik3.wav  veoma_dugi   29.104  0.299  103.647

### Konačno poređenje: FLEURS i prirodni govor, bez mešanja korpusa

Za svaki korpus zasebno prikazuju se corpus WER (zbir S+D+I kroz snimke / zbir referentnih reči), prosečni WER, RTF i simulirano vreme do rezultata. Dodatno: poređenje po govornicima i dužinskim grupama na 40 snimaka. Razlike na 40 razvojnih snimaka **nisu nezavisna procena generalizacije**.

In [21]:
# sumiraj_nacin() definisan je u FLEURS uporednoj ćeliji iznad.
poredjenje_40 = pd.DataFrame([
    sumiraj_nacin(df_40_stream, 'STREAMING'),
    sumiraj_nacin(df_40_ceo, 'CEO_SNIMAK')
])
poredjenje_40.insert(0, 'Skup', '40_prirodnih_razvojni_benchmark')
poredjenje_40.to_csv(REZULTATI_40_DIR / '99_40_UPoredni_rezime.csv', index=False, encoding='utf-8-sig')

parovi_40 = df_40_stream[['Broj','Fajl','Govornik','Grupa','WER_pct','RTF','TTFR_s']].merge(
    df_40_ceo[['Broj','Fajl','WER_pct','RTF','TTFR_s']], on=['Broj','Fajl'],
    suffixes=('_streaming','_ceo'), validate='one_to_one')
parovi_40['Razlika_WER_pp_stream_minus_ceo'] = parovi_40.WER_pct_streaming - parovi_40.WER_pct_ceo
parovi_40['Razlika_RTF_stream_minus_ceo'] = parovi_40.RTF_streaming - parovi_40.RTF_ceo
parovi_40.to_csv(REZULTATI_40_DIR / '99_40_UPoredno_po_snimku.csv', index=False, encoding='utf-8-sig')

poredjenje_fleurs = poredjenje.copy()
poredjenje_fleurs.insert(0, 'Skup', '30_FLEURS_prethodno_korisceni_u_03')
poredjenje_svi = pd.concat([poredjenje_40, poredjenje_fleurs], ignore_index=True)
poredjenje_svi.to_csv(REZULTATI_40_DIR / '99_UPoredni_rezime_DVA_SKUPA.csv', index=False, encoding='utf-8-sig')
print('Dva skupa, odvojene metrike (ne sabirati corpus WER preko korpusa):')
display(poredjenje_svi[['Skup','Nacin','Broj_snimaka','Corpus_WER_pct','Prosecan_WER_pct','Prosecan_RTF','Prosecna_TTFR_s']].round(3))
print('Razlika corpus WER na 40 snimaka (streaming - ceo), pp:',
      round(float(poredjenje_40.iloc[0].Corpus_WER_pct - poredjenje_40.iloc[1].Corpus_WER_pct),3))

def grupni_rezime(tabela, kolona, nacin):
    redovi=[]
    for naziv, deo in tabela.groupby(kolona):
        z = sumiraj_nacin(deo, nacin)
        redovi.append({kolona:naziv, 'Nacin':nacin, **{k:z[k] for k in ['Broj_snimaka','Corpus_WER_pct','Prosecan_WER_pct','Prosecan_RTF','Prosecna_TTFR_s']}})
    return redovi

po_grupama = pd.DataFrame(
    grupni_rezime(df_40_stream, 'Grupa', 'STREAMING') + grupni_rezime(df_40_ceo, 'Grupa', 'CEO_SNIMAK'))
po_govornicima = pd.DataFrame(
    grupni_rezime(df_40_stream, 'Govornik', 'STREAMING') + grupni_rezime(df_40_ceo, 'Govornik', 'CEO_SNIMAK'))
po_grupama.to_csv(REZULTATI_40_DIR/'99_40_po_grupama.csv',index=False,encoding='utf-8-sig')
po_govornicima.to_csv(REZULTATI_40_DIR/'99_40_po_govornicima.csv',index=False,encoding='utf-8-sig')
print('Po grupama:'); display(po_grupama.round(3))
print('Po govornicima:'); display(po_govornicima.round(3))
print('Po snimcima:'); display(parovi_40.round(3))

Dva skupa, odvojene metrike (ne sabirati corpus WER preko korpusa):

,Skup,Nacin,Broj_snimaka,Corpus_WER_pct,Prosecan_WER_pct,Prosecan_RTF,Prosecna_TTFR_s
0,40_prirodnih_razvojni_benchmark,STREAMING,40,34.368,35.004,1.358,12.460
1,40_prirodnih_razvojni_benchmark,CEO_SNIMAK,40,23.233,22.440,0.434,33.905
2,30_FLEURS_prethodno_korisceni_u_03,STREAMING,30,49.211,49.532,1.125,10.574
3,30_FLEURS_prethodno_korisceni_u_03,CEO_SNIMAK,30,49.054,48.165,0.886,21.738

Razlika corpus WER na 40 snimaka (streaming - ceo), pp: 11.135
Po grupama:

,Grupa,Nacin,Broj_snimaka,Corpus_WER_pct,Prosecan_WER_pct,Prosecan_RTF,Prosecna_TTFR_s
0,dugi,STREAMING,10,34.488,34.798,1.200,12.808
1,kratki,STREAMING,10,32.414,32.544,1.790,12.910
2,srednji,STREAMING,15,37.156,37.449,1.300,12.171
3,veoma_dugi,STREAMING,5,32.893,33.003,0.987,11.735
4,dugi,CEO_SNIMAK,10,27.228,27.607,0.396,44.349
5,kratki,CEO_SNIMAK,10,17.241,17.265,0.571,10.799
6,srednji,CEO_SNIMAK,15,22.477,22.719,0.395,21.319
7,veoma_dugi,CEO_SNIMAK,5,21.439,21.624,0.356,96.985

Po govornicima:

,Govornik,Nacin,Broj_snimaka,Corpus_WER_pct,Prosecan_WER_pct,Prosecan_RTF,Prosecna_TTFR_s
0,govornik1,STREAMING,13,39.072,38.712,1.413,12.928
1,govornik2,STREAMING,13,22.901,23.193,1.146,11.736
2,govornik3,STREAMING,14,41.667,42.528,1.505,12.698
3,govornik1,CEO_SNIMAK,13,26.112,23.744,0.446,28.679
4,govornik2,CEO_SNIMAK,13,10.534,11.764,0.372,38.107
5,govornik3,CEO_SNIMAK,14,33.046,31.144,0.482,34.855

Po snimcima:

,Broj,Fajl,Govornik,Grupa,WER_pct_streaming,RTF_streaming,TTFR_s_streaming,WER_pct_ceo,RTF_ceo,TTFR_s_ceo,Razlika_WER_pp_stream_minus_ceo,Razlika_RTF_stream_minus_ceo
0,1,1govornik1.wav,govornik1,kratki,46.154,1.401,12.099,15.385,0.499,11.396,30.769,0.903
1,2,2govornik1.wav,govornik1,kratki,28.571,1.799,12.855,7.143,0.528,10.361,21.429,1.271
2,3,3govornik1.wav,govornik1,kratki,26.667,2.054,13.114,20.000,0.554,9.059,6.667,1.500
3,4,4govornik1.wav,govornik1,kratki,28.571,1.658,13.239,21.429,0.509,11.000,7.143,1.150
4,5,5govornik2.wav,govornik2,kratki,20.000,1.075,11.461,13.333,0.439,13.428,6.667,0.637
5,6,6govornik2.wav,govornik2,kratki,26.667,1.502,13.072,13.333,0.516,11.968,13.333,0.986
6,7,7govornik2.wav,govornik2,kratki,28.571,1.497,13.435,14.286,0.472,12.854,14.286,1.025
7,8,8govornik3.wav,govornik3,kratki,25.000,2.383,13.303,12.500,0.740,9.069,12.500,1.644
8,9,9govornik3.wav,govornik3,kratki,66.667,2.399,13.432,26.667,0.753,9.364,40.000,1.646
9,10,10govornik3.wav,govornik3,kratki,28.571,2.127,13.088,28.571,0.696,9.489,0.000,1.432
10,11,11govornik1.wav,govornik1,srednji,32.258,1.345,12.147,19.355,0.369,22.535,12.903,0.976
11,12,12govornik1.wav,govornik1,srednji,45.161,1.321,13.139,29.032,0.464,18.626,16.129,0.857
12,13,13govornik1.wav,govornik1,srednji,34.483,1.386,12.515,31.034,0.416,21.356,3.448,0.970
13,14,14govornik1.wav,govornik1,srednji,58.621,1.411,12.872,27.586,0.410,21.994,31.034,1.001
14,15,15govornik1.wav,govornik1,srednji,57.143,1.212,12.798,35.714,0.372,23.907,21.429,0.840
15,16,16govornik2.wav,govornik2,srednji,27.273,1.025,9.443,12.121,0.322,23.325,15.152,0.703
16,17,17govornik2.wav,govornik2,srednji,10.714,1.317,13.564,3.571,0.345,22.303,7.143,0.972
17,18,18govornik2.wav,govornik2,srednji,21.429,0.986,9.781,10.714,0.313,23.899,10.714,0.673
18,19,19govornik2.wav,govornik2,srednji,36.667,1.257,11.829,16.667,0.351,22.837,20.000,0.906
19,20,20govornik2.wav,govornik2,srednji,19.231,1.021,9.190,15.385,0.340,21.724,3.846,0.681
20,21,21govornik3.wav,govornik3,srednji,55.556,1.099,11.595,37.037,0.442,21.014,18.519,0.657
21,22,22govornik3.wav,govornik3,srednji,30.000,1.207,13.260,16.667,0.426,20.893,13.333,0.781
22,23,23govornik3.wav,govornik3,srednji,56.522,1.734,13.282,34.783,0.475,18.014,21.739,1.259
23,24,24govornik3.wav,govornik3,srednji,41.379,1.581,13.620,27.586,0.448,16.860,13.793,1.133
24,25,25govornik3.wav,govornik3,srednji,35.294,1.597,13.527,23.529,0.434,20.504,11.765,1.164
25,26,26govornik1.wav,govornik1,dugi,34.483,1.232,13.702,24.138,0.434,44.592,10.345,0.798
26,27,27govornik1.wav,govornik1,dugi,33.871,1.212,12.945,17.742,0.415,38.852,16.129,0.797
27,28,28govornik1.wav,govornik1,dugi,36.508,1.308,13.188,28.571,0.471,45.159,7.937,0.836
28,29,29govornik2.wav,govornik2,dugi,31.148,1.188,13.407,19.672,0.352,47.272,11.475,0.836
29,30,30govornik2.wav,govornik2,dugi,12.698,1.073,12.890,7.937,0.337,50.477,4.762,0.736
30,31,31govornik2.wav,govornik2,dugi,20.312,1.080,13.774,9.375,0.345,47.031,10.938,0.735
31,32,32govornik3.wav,govornik3,dugi,43.333,1.394,13.169,45.000,0.407,39.341,-1.667,0.988
32,33,33govornik3.wav,govornik3,dugi,43.939,1.123,8.994,39.394,0.392,43.504,4.545,0.732
33,34,34govornik3.wav,govornik3,dugi,49.091,1.094,12.985,50.909,0.387,45.884,-1.818,0.708
34,35,35govornik3.wav,govornik3,dugi,42.593,1.291,13.022,33.333,0.424,41.380,9.259,0.867
35,36,36govornik1.wav,govornik1,veoma_dugi,40.769,1.023,13.455,31.538,0.362,93.991,9.231,0.661
36,37,37govornik2.wav,govornik2,veoma_dugi,21.986,0.858,8.792,8.511,0.352,111.414,13.475,0.506
37,38,38govornik2.wav,govornik2,veoma_dugi,24.818,1.020,11.935,8.029,0.348,86.865,16.788,0.672
38,39,39govornik3.wav,govornik3,veoma_dugi,44.604,1.135,13.023,30.935,0.422,89.007,13.669,0.713
39,40,40govornik3.wav,govornik3,veoma_dugi,32.836,0.898,11.470,29.104,0.299,103.647,3.731,0.598

## Metodološka napomena

- Skup ima 30 lokalnih srpskih FLEURS snimaka sa referencama iz zvaničnog `sr_rs/test.tsv`.
- Profil iz 08 mora biti izabran **pre** evaluacije; FLEURS WER se ne sme koristiti za naknadno biranje konfiguracije.
- `TTFR_s` je simulirano vreme prvog rezultata na osnovu dolaska segmenta i izmerenog trajanja dekodiranja, ne realno merenje mikrofonskog streaminga.
- Za vrlo kratke FLEURS snimke često postoji samo jedan segment, pa se prednosti preklapanja i konteksta ne mogu pouzdano oceniti samo na ovom skupu.
- Brojevi WER/RTF/TTFR nastaju tek nakon lokalnog izvršavanja modela; ovaj notebook ne tvrdi da je ASR evaluacija unapred izvršena.
- Dodat je kontrolni prolaz nad celim snimkom bez segmentacije. Rezultati se čuvaju odvojeno; postojeći streaming CSV-ovi ostaju netaknuti.
- TTFR celog snimka predstavlja vreme do kompletnog batch rezultata (trajanje + obrada), dok streaming TTFR predstavlja simulirani prvi parcijalni rezultat; nisu identične vrste korisničkog odziva.
- FLEURS snimci su često kratki; kada postoji samo jedan streaming segment, poređenje ne izoluje uticaj overlap-a.